from ctypes import c_uint32

EXTRA_CHAR = 0
V2GTP_HEADER_LENGTH = 8
V2GTP_VERSION = 0x01
V2GTP_VERSION_INV = 0xFE
V2GTP_EXI_TYPE = 0x8001
EXTRA_CHAR = 0
EXTRA_CHAR = 0
BUFFER_SIZE = 256
ERROR_UNEXPECTED_REQUEST_MESSAGE = -601
ERROR_UNEXPECTED_SESSION_SETUP_RESP_MESSAGE = -602
ERROR_UNEXPECTED_SERVICE_DISCOVERY_RESP_MESSAGE = -602
ERROR_UNEXPECTED_SERVICE_DETAILS_RESP_MESSAGE = -603
ERROR_UNEXPECTED_PAYMENT_SERVICE_SELECTION_RESP_MESSAGE = -604
ERROR_UNEXPECTED_PAYMENT_DETAILS_RESP_MESSAGE = -605
ERROR_UNEXPECTED_AUTHORIZATION_RESP_MESSAGE = -606
ERROR_UNEXPECTED_CHARGE_PARAMETER_DISCOVERY_RESP_MESSAGE = -607
ERROR_UNEXPECTED_POWER_DELIVERY_RESP_MESSAGE = -608
ERROR_UNEXPECTED_CHARGING_STATUS_RESP_MESSAGE = -609
ERROR_UNEXPECTED_METERING_RECEIPT_RESP_MESSAGE = -610
ERROR_UNEXPECTED_SESSION_STOP_RESP_MESSAGE = -611
ERROR_UNEXPECTED_CABLE_CHECK_RESP_MESSAGE = -612
ERROR_UNEXPECTED_PRE_CHARGE_RESP_MESSAGE = -612
ERROR_UNEXPECTED_CURRENT_DEMAND_RESP_MESSAGE = -613
ERROR_UNEXPECTED_WELDING_DETECTION_RESP_MESSAGE = -614
EXTRA_CHAR = 0
EXI_DEBUG = 0
BUFFER_SIZE = 4096
EXTRA_CHAR = 0
CODE_VERSION_EXI = 1
CODE_VERSION_SAMPLE = 2
EXTRA_CHAR = 0
EXTRA_CHAR = 0
SUPPORT_YES = 1
SUPPORT_NO = 2
DEPLOY_ISO2_CODEC = SUPPORT_NO
DEPLOY_ISO2_CODEC_FRAGMENT = SUPPORT_NO
UNION_YES = 1
UNION_NO = 2
SAVE_MEMORY_WITH_UNNAMED_UNION = UNION_YES
iso2RSAKeyValueType_Modulus_BYTES_SIZE = 350
iso2RSAKeyValueType_Exponent_BYTES_SIZE = 350
iso2MeterInfoType_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso2MeterInfoType_SigMeterReading_BYTES_SIZE = 64
iso2ServiceListType_Service_ARRAY_SIZE = 8
iso2MagneticVectorSetupType_GAID_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ObjectType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ObjectType_MimeType_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ObjectType_Encoding_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ObjectType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SensorOrderListType_SensorPosition_ARRAY_SIZE = 5
iso2MeasurementDataListType_MeasurementData_ARRAY_SIZE = 5
iso2SignaturePropertyType_Target_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignaturePropertyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignaturePropertyType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2TransformType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso2TransformType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2TransformType_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2TransformType_XPath_ARRAY_SIZE = 1
iso2EMAIDType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2EMAIDType_CONTENT_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2DSAKeyValueType_P_BYTES_SIZE = 350
iso2DSAKeyValueType_Q_BYTES_SIZE = 350
iso2DSAKeyValueType_G_BYTES_SIZE = 350
iso2DSAKeyValueType_Y_BYTES_SIZE = 350
iso2DSAKeyValueType_J_BYTES_SIZE = 350
iso2DSAKeyValueType_Seed_BYTES_SIZE = 350
iso2DSAKeyValueType_PgenCounter_BYTES_SIZE = 350
iso2MeteringReceiptReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2MeteringReceiptReqType_SessionID_BYTES_SIZE = 8
iso2KeyValueType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2AuthorizationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2AuthorizationReqType_GenChallenge_BYTES_SIZE = 16
iso2SPKIDataType_SPKISexp_BYTES_SIZE = 350
iso2SPKIDataType_SPKISexp_ARRAY_SIZE = 1
iso2SPKIDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignatureMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso2SignatureMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SessionSetupReqType_EVCCID_BYTES_SIZE = 6
iso2CanonicalizationMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso2CanonicalizationMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2DigestMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso2DigestMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SubCertificatesType_Certificate_BYTES_SIZE = 800
iso2SubCertificatesType_Certificate_ARRAY_SIZE = 4
iso2ContractSignatureEncryptedPrivateKeyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ContractSignatureEncryptedPrivateKeyType_CONTENT_BYTES_SIZE = 350
iso2MagneticVectorSetupListType_MagneticVectorSetup_ARRAY_SIZE = 5
iso2X509IssuerSerialType_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2PGPDataType_PGPKeyID_BYTES_SIZE = 350
iso2PGPDataType_PGPKeyPacket_BYTES_SIZE = 350
iso2PGPDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ServiceIDListType_ServiceID_ARRAY_SIZE = 10
iso2SignatureValueType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignatureValueType_CONTENT_BYTES_SIZE = 350
iso2DiffieHellmanPublickeyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2DiffieHellmanPublickeyType_CONTENT_BYTES_SIZE = 350
iso2X509DataType_X509IssuerSerial_ARRAY_SIZE = 1
iso2X509DataType_X509SKI_BYTES_SIZE = 350
iso2X509DataType_X509SKI_ARRAY_SIZE = 1
iso2X509DataType_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2X509DataType_X509SubjectName_ARRAY_SIZE = 1
iso2X509DataType_X509Certificate_BYTES_SIZE = 350
iso2X509DataType_X509Certificate_ARRAY_SIZE = 1
iso2X509DataType_X509CRL_BYTES_SIZE = 350
iso2X509DataType_X509CRL_ARRAY_SIZE = 1
iso2X509DataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2DC_BidirectionalControlResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2ChargingStatusResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2SignaturePropertiesType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignaturePropertiesType_SignatureProperty_ARRAY_SIZE = 1
iso2PMaxScheduleEntryType_PMax_ARRAY_SIZE = 3
iso2ConsumptionCostType_Cost_ARRAY_SIZE = 3
iso2PaymentOptionListType_PaymentOption_ARRAY_SIZE = 2
iso2TransformsType_Transform_ARRAY_SIZE = 1
iso2ParameterType_Name_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ParameterType_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2CertificateChainType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2CertificateChainType_Certificate_BYTES_SIZE = 800
iso2SessionSetupResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2ReferenceType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ReferenceType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ReferenceType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ReferenceType_DigestValue_BYTES_SIZE = 350
iso2SensorListType_Sensor_ARRAY_SIZE = 5
iso2ParameterSetType_Parameter_ARRAY_SIZE = 16
iso2PaymentDetailsResType_GenChallenge_BYTES_SIZE = 16
iso2AC_BidirectionalControlResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2MinimumPMaxRequestType_MinimumPMaxScheduleEntry_ARRAY_SIZE = 3
iso2PaymentDetailsReqType_eMAID_CHARACTERS_SIZE = 15 + EXTRA_CHAR
iso2SalesTariffEntryType_ConsumptionCost_ARRAY_SIZE = 3
iso2MagneticVectorType_GAID_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ManifestType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2ManifestType_Reference_ARRAY_SIZE = 1
iso2SelectedServiceListType_SelectedService_ARRAY_SIZE = 16
iso2ListOfRootCertificateIDsType_RootCertificateID_ARRAY_SIZE = 20
iso2CurrentDemandResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2SensorPackageType_SensorMeasurements_ARRAY_SIZE = 5
iso2PowerDemandResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso2ChargingProfileType_ProfileEntry_ARRAY_SIZE = 24
iso2SalesTariffType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SalesTariffType_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso2SalesTariffType_SalesTariffEntry_ARRAY_SIZE = 5
iso2SignedInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignedInfoType_Reference_ARRAY_SIZE = 1
iso2RetrievalMethodType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2RetrievalMethodType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2MagneticVectorListType_MagneticVector_ARRAY_SIZE = 5
iso2ServiceParameterListType_ParameterSet_ARRAY_SIZE = 5
iso2PMaxScheduleType_PMaxScheduleEntry_ARRAY_SIZE = 5
iso2CertificateUpdateReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2CertificateUpdateReqType_eMAID_CHARACTERS_SIZE = 15 + EXTRA_CHAR
iso2CertificateInstallationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2CertificateInstallationReqType_OEMProvisioningCert_BYTES_SIZE = 800
iso2SensorPackageListType_SensorPackage_ARRAY_SIZE = 5
iso2KeyInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2KeyInfoType_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2KeyInfoType_KeyName_ARRAY_SIZE = 1
iso2KeyInfoType_KeyValue_ARRAY_SIZE = 1
iso2KeyInfoType_RetrievalMethod_ARRAY_SIZE = 1
iso2KeyInfoType_X509Data_ARRAY_SIZE = 1
iso2KeyInfoType_PGPData_ARRAY_SIZE = 1
iso2KeyInfoType_SPKIData_ARRAY_SIZE = 1
iso2KeyInfoType_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2KeyInfoType_MgmtData_ARRAY_SIZE = 1
iso2KeyInfoType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignatureType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2SignatureType_Object_ARRAY_SIZE = 1
iso2SAScheduleListType_SAScheduleTuple_ARRAY_SIZE = 3
iso2MessageHeaderType_SessionID_BYTES_SIZE = 8
EXIDocument_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_DigestValue_BYTES_SIZE = 350
EXIFragment_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_PgenCounter_BYTES_SIZE = 350
EXIFragment_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_SessionID_BYTES_SIZE = 8
EXIFragment_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_OEMProvisioningCert_BYTES_SIZE = 800
EXIFragment_P_BYTES_SIZE = 350
EXIFragment_Q_BYTES_SIZE = 350
EXIFragment_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_G_BYTES_SIZE = 350
EXIFragment_J_BYTES_SIZE = 350
EXIFragment_Y_BYTES_SIZE = 350
EXIFragment_DigestValue_BYTES_SIZE = 350
EXIFragment_EVCCID_BYTES_SIZE = 6
EXIFragment_PGPKeyID_BYTES_SIZE = 350
EXIFragment_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_X509SKI_BYTES_SIZE = 350
EXIFragment_Certificate_BYTES_SIZE = 800
EXIFragment_Modulus_BYTES_SIZE = 350
EXIFragment_SigMeterReading_BYTES_SIZE = 64
EXIFragment_Exponent_BYTES_SIZE = 350
EXIFragment_PGPKeyPacket_BYTES_SIZE = 350
EXIFragment_Seed_BYTES_SIZE = 350
EXIFragment_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_X509CRL_BYTES_SIZE = 350
EXIFragment_SPKISexp_BYTES_SIZE = 350
EXIFragment_X509Certificate_BYTES_SIZE = 350
EXIFragment_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
EXIFragment_GenChallenge_BYTES_SIZE = 16
EXIFragment_GAID_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso2vehicleSpaceType_AutoParking = 0
iso2vehicleSpaceType_MVGuideManual = 1
iso2vehicleSpaceType_Manual = 2
iso2operationModeType_Ready = 0
iso2operationModeType_NotReady = 1
iso2EVSENotificationType_StopCharging = 0
iso2EVSENotificationType_ReNegotiation = 1
iso2valueType_bool = 0
iso2valueType_byte = 1
iso2valueType_short = 2
iso2valueType_int = 3
iso2valueType_physicalValue = 4
iso2valueType_string = 5
iso2EVCheckInStatusType_CheckIn = 0
iso2EVCheckInStatusType_Processing = 1
iso2EVCheckInStatusType_Completed = 2
iso2mechanicalChargingDeviceStatusType_Home = 0
iso2mechanicalChargingDeviceStatusType_Moving = 1
iso2mechanicalChargingDeviceStatusType_EndPosition = 2
iso2chargeProgressType_Start = 0
iso2chargeProgressType_Stop = 1
iso2chargeProgressType_Renegotiate = 2
iso2FODStatusType_ObjectOnPad = 0
iso2FODStatusType_PadClear = 1
iso2FODStatusType_UnknownError = 2
iso2costKindType_relativePricePercentage = 0
iso2costKindType_RenewableGenerationPercentage = 1
iso2costKindType_CarbonDioxideEmission = 2
iso2EVOperationType_Charge = 0
iso2EVOperationType_BPT = 1
iso2serviceCategoryType_EVCharging = 0
iso2serviceCategoryType_Internet = 1
iso2serviceCategoryType_ContractCertificate = 2
iso2serviceCategoryType_OtherCustom = 3
iso2parkingMethodType_AutoParking = 0
iso2parkingMethodType_MVGuideManual = 1
iso2parkingMethodType_Manual = 2
iso2responseCodeType_OK = 0
iso2responseCodeType_OK_NewSessionEstablished = 1
iso2responseCodeType_OK_OldSessionJoined = 2
iso2responseCodeType_OK_CertificateExpiresSoon = 3
iso2responseCodeType_OK_IsolationValid = 4
iso2responseCodeType_OK_IsolationWarning = 5
iso2responseCodeType_WARNING_CertificateExpired = 6
iso2responseCodeType_WARNING_NoCertificateAvailable = 7
iso2responseCodeType_WARNING_CertValidationError = 8
iso2responseCodeType_WARNING_CertVerificationError = 9
iso2responseCodeType_WARNING_ContractCanceled = 10
iso2responseCodeType_FAILED = 11
iso2responseCodeType_FAILED_SequenceError = 12
iso2responseCodeType_FAILED_ServiceIDInvalid = 13
iso2responseCodeType_FAILED_UnknownSession = 14
iso2responseCodeType_FAILED_ServiceSelectionInvalid = 15
iso2responseCodeType_FAILED_SignatureError = 16
iso2responseCodeType_FAILED_PaymentSelectionInvalid = 17
iso2responseCodeType_FAILED_ChallengeInvalid = 18
iso2responseCodeType_FAILED_WrongChargeParameter = 19
iso2responseCodeType_FAILED_IsolationFault = 20
iso2responseCodeType_FAILED_PowerDeliveryNotApplied = 21
iso2responseCodeType_FAILED_TariffSelectionInvalid = 22
iso2responseCodeType_FAILED_ChargingProfileInvalid = 23
iso2responseCodeType_FAILED_MeteringSignatureNotValid = 24
iso2responseCodeType_FAILED_NoChargeServiceSelected = 25
iso2responseCodeType_FAILED_WrongEnergyTransferMode = 26
iso2responseCodeType_FAILED_ContactorError = 27
iso2responseCodeType_FAILED_CertificateRevoked = 28
iso2responseCodeType_FAILED_CertificateNotYetValid = 29
iso2chargingSessionType_Terminate = 0
iso2chargingSessionType_Pause = 1
iso2EVSEProcessingType_Finished = 0
iso2EVSEProcessingType_Ongoing = 1
iso2EVSEProcessingType_Ongoing_WaitingForCustomerInteraction = 2
iso2paymentOptionType_Contract = 0
iso2paymentOptionType_ExternalPayment = 1
iso2EVSECheckOutStatusType_Scheduled = 0
iso2EVSECheckOutStatusType_Completed = 1
iso2EVCheckOutStatusType_CheckOut = 0
iso2EVCheckOutStatusType_Processing = 1
iso2EVCheckOutStatusType_Completed = 2
iso2electricalChargingDeviceStatusType_Connected = 0
iso2electricalChargingDeviceStatusType_Disconnected = 1
iso2EVSEErrorCodeType_RESSTemperatureInhibit = 0
iso2EVSEErrorCodeType_ChargerConnectorLockFault = 1
iso2EVSEErrorCodeType_ChargingCurrentdifferential = 2
iso2EVSEErrorCodeType_ChargingVoltageOutOfRange = 3
iso2EVSEErrorCodeType_ChargingSystemIncompatibility = 4
iso2EVSEErrorCodeType_Reserved_A = 5
iso2EVSEErrorCodeType_Reserved_B = 6
iso2EVSEErrorCodeType_Reserved_C = 7
iso2EVErrorCodeType_RESSTemperatureInhibit = 0
iso2EVErrorCodeType_EVShiftPosition = 1
iso2EVErrorCodeType_ChargerConnectorLockFault = 2
iso2EVErrorCodeType_EVRESSMalfunction = 3
iso2EVErrorCodeType_ChargingCurrentdifferential = 4
iso2EVErrorCodeType_ChargingVoltageOutOfRange = 5
iso2EVErrorCodeType_ChargingSystemIncompatibility = 6
iso2EVErrorCodeType_Reserved_A = 7
iso2EVErrorCodeType_Reserved_B = 8
iso2EVErrorCodeType_Reserved_C = 9
iso2paymentOptionType_Contract = 0
iso2paymentOptionType_ExternalPayment = 1
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
SUPPORT_YES = 1
SUPPORT_NO = 2
DEPLOY_XMLDSIG_CODEC = SUPPORT_NO
DEPLOY_XMLDSIG_CODEC_FRAGMENT = SUPPORT_NO
UNION_YES = 1
UNION_NO = 2
SAVE_MEMORY_WITH_UNNAMED_UNION = UNION_YES
xmldsigCanonicalizationMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
xmldsigCanonicalizationMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigObjectType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigObjectType_MimeType_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigObjectType_Encoding_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigObjectType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigTransformType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
xmldsigTransformType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigTransformType_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigTransformType_XPath_ARRAY_SIZE = 1
xmldsigSignatureMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
xmldsigSignatureMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigDigestMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
xmldsigDigestMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignatureValueType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignatureValueType_CONTENT_BYTES_SIZE = 350
xmldsigX509IssuerSerialType_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignaturePropertyType_Target_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignaturePropertyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignaturePropertyType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigRSAKeyValueType_Modulus_BYTES_SIZE = 350
xmldsigRSAKeyValueType_Exponent_BYTES_SIZE = 350
xmldsigPGPDataType_PGPKeyID_BYTES_SIZE = 350
xmldsigPGPDataType_PGPKeyPacket_BYTES_SIZE = 350
xmldsigPGPDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigTransformsType_Transform_ARRAY_SIZE = 1
xmldsigX509DataType_X509IssuerSerial_ARRAY_SIZE = 1
xmldsigX509DataType_X509SKI_BYTES_SIZE = 350
xmldsigX509DataType_X509SKI_ARRAY_SIZE = 1
xmldsigX509DataType_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigX509DataType_X509SubjectName_ARRAY_SIZE = 1
xmldsigX509DataType_X509Certificate_BYTES_SIZE = 350
xmldsigX509DataType_X509Certificate_ARRAY_SIZE = 1
xmldsigX509DataType_X509CRL_BYTES_SIZE = 350
xmldsigX509DataType_X509CRL_ARRAY_SIZE = 1
xmldsigX509DataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigDSAKeyValueType_P_BYTES_SIZE = 350
xmldsigDSAKeyValueType_Q_BYTES_SIZE = 350
xmldsigDSAKeyValueType_G_BYTES_SIZE = 350
xmldsigDSAKeyValueType_Y_BYTES_SIZE = 350
xmldsigDSAKeyValueType_J_BYTES_SIZE = 350
xmldsigDSAKeyValueType_Seed_BYTES_SIZE = 350
xmldsigDSAKeyValueType_PgenCounter_BYTES_SIZE = 350
xmldsigReferenceType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigReferenceType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigReferenceType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigReferenceType_DigestValue_BYTES_SIZE = 350
xmldsigSPKIDataType_SPKISexp_BYTES_SIZE = 350
xmldsigSPKIDataType_SPKISexp_ARRAY_SIZE = 1
xmldsigSPKIDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigManifestType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigManifestType_Reference_ARRAY_SIZE = 1
xmldsigRetrievalMethodType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigRetrievalMethodType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignedInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignedInfoType_Reference_ARRAY_SIZE = 1
xmldsigSignaturePropertiesType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignaturePropertiesType_SignatureProperty_ARRAY_SIZE = 1
xmldsigKeyValueType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigKeyInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigKeyInfoType_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigKeyInfoType_KeyName_ARRAY_SIZE = 1
xmldsigKeyInfoType_KeyValue_ARRAY_SIZE = 1
xmldsigKeyInfoType_RetrievalMethod_ARRAY_SIZE = 1
xmldsigKeyInfoType_X509Data_ARRAY_SIZE = 1
xmldsigKeyInfoType_PGPData_ARRAY_SIZE = 1
xmldsigKeyInfoType_SPKIData_ARRAY_SIZE = 1
xmldsigKeyInfoType_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigKeyInfoType_MgmtData_ARRAY_SIZE = 1
xmldsigKeyInfoType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignatureType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
xmldsigSignatureType_Object_ARRAY_SIZE = 1
EXIDocument_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_DigestValue_BYTES_SIZE = 350
EXIFragment_DigestValue_BYTES_SIZE = 350
EXIFragment_SPKISexp_BYTES_SIZE = 350
EXIFragment_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_PGPKeyID_BYTES_SIZE = 350
EXIFragment_PGPKeyPacket_BYTES_SIZE = 350
EXIFragment_Exponent_BYTES_SIZE = 350
EXIFragment_P_BYTES_SIZE = 350
EXIFragment_Q_BYTES_SIZE = 350
EXIFragment_Seed_BYTES_SIZE = 350
EXIFragment_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_X509Certificate_BYTES_SIZE = 350
EXIFragment_G_BYTES_SIZE = 350
EXIFragment_J_BYTES_SIZE = 350
EXIFragment_X509SKI_BYTES_SIZE = 350
EXIFragment_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_Modulus_BYTES_SIZE = 350
EXIFragment_X509CRL_BYTES_SIZE = 350
EXIFragment_Y_BYTES_SIZE = 350
EXIFragment_PgenCounter_BYTES_SIZE = 350
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
BYTE_ARRAY = 1
FILE_STREAM = 2
EXI_STREAM = BYTE_ARRAY
STATIC_ALLOCATION = 1
DYNAMIC_ALLOCATION = 2
MEMORY_ALLOCATION = STATIC_ALLOCATION
STRING_REPRESENTATION_ASCII = 1
STRING_REPRESENTATION_UCS = 2
EXTRA_CHAR = 1
EXTRA_CHAR = 0
EXI_ELEMENT_STACK_SIZE = 24
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXI_ERROR_INPUT_STREAM_EOF = -10
EXI_ERROR_OUTPUT_STREAM_EOF = -11
EXI_ERROR_INPUT_FILE_HANDLE = -12
EXI_ERROR_OUTPUT_FILE = -13
EXI_ERROR_OUT_OF_BOUNDS = -100
EXI_ERROR_OUT_OF_STRING_BUFFER = -101
EXI_ERROR_OUT_OF_BYTE_BUFFER = -103
EXI_ERROR_OUT_OF_GRAMMAR_STACK = -104
EXI_ERROR_OUT_OF_RUNTIME_GRAMMAR_STACK = -105
EXI_ERROR_OUT_OF_QNAMES = -106
EXI_ERROR_UNKOWN_GRAMMAR_ID = -108
EXI_ERROR_UNKOWN_EVENT = -109
EXI_ERROR_UNKOWN_EVENT_CODE = -110
EXI_ERROR_UNEXPECTED_EVENT_LEVEL1 = -111
EXI_ERROR_UNEXPECTED_EVENT_LEVEL2 = -112
EXI_ERROR_UNEXPECTED_START_DOCUMENT = -113
EXI_ERROR_UNEXPECTED_END_DOCUMENT = -114
EXI_ERROR_UNEXPECTED_START_ELEMENT = -115
EXI_ERROR_UNEXPECTED_START_ELEMENT_NS = -116
EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC = -117
EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC_UNDECLARED = -118
EXI_ERROR_UNEXPECTED_END_ELEMENT = -119
EXI_ERROR_UNEXPECTED_CHARACTERS = -120
EXI_ERROR_UNEXPECTED_ATTRIBUTE = -121
EXI_ERROR_UNEXPECTED_ATTRIBUTE_NS = -122
EXI_ERROR_UNEXPECTED_ATTRIBUTE_GENERIC = -123
EXI_ERROR_UNEXPECTED_ATTRIBUTE_GENERIC_UNDECLARED = -124
EXI_ERROR_UNEXPECTED_ATTRIBUTE_XSI_TYPE = -125
EXI_ERROR_UNEXPECTED_ATTRIBUTE_XSI_NIL = -126
EXI_ERROR_UNEXPECTED_GRAMMAR_ID = -127
EXI_ERROR_UNEXPECTED_ATTRIBUTE_MOVE_TO_CONTENT_RULE = -128
EXI_UNSUPPORTED_NBIT_INTEGER_LENGTH = -132
EXI_UNSUPPORTED_EVENT_CODE_CHARACTERISTICS = -133
EXI_UNSUPPORTED_INTEGER_VALUE = -134
EXI_NEGATIVE_UNSIGNED_INTEGER_VALUE = -135
EXI_UNSUPPORTED_LIST_VALUE_TYPE = -136
EXI_UNSUPPORTED_HEADER_COOKIE = -137
EXI_UNSUPPORTED_HEADER_OPTIONS = -138
EXI_UNSUPPORTED_GLOBAL_ATTRIBUTE_VALUE_TYPE = -139
EXI_UNSUPPORTED_DATATYPE = -140
EXI_UNSUPPORTED_STRING_VALUE_TYPE = -141
EXI_UNSUPPORTED_INTEGER_VALUE_TYPE = -142
EXI_UNSUPPORTED_DATETIME_TYPE = -143
EXI_UNSUPPORTED_FRAGMENT_ELEMENT = -144
EXI_UNSUPPORTED_GRAMMAR_LEARNING_CH = -150
EXI_ERROR_STRINGVALUES_NOT_SUPPORTED = -160
EXI_ERROR_STRINGVALUES_OUT_OF_ENTRIES = -161
EXI_ERROR_STRINGVALUES_OUT_OF_MEMORY = -162
EXI_ERROR_STRINGVALUES_OUT_OF_BOUND = -163
EXI_ERROR_STRINGVALUES_CHARACTER = -164
EXI_ERROR_UNEXPECTED_BYTE_VALUE = -200
EXI_ERROR_CONVERSION_NO_ASCII_CHARACTERS = -300
EXI_ERROR_CONVERSION_TYPE_TO_STRING = -301
EXI_DEVIANT_SUPPORT_NOT_DEPLOYED = -500
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
BITS_IN_BYTE = 8
DATETIME_YEAR_OFFSET = 2000
DATETIME_NUMBER_BITS_MONTHDAY = 9
DATETIME_NUMBER_BITS_TIME = 17
DATETIME_NUMBER_BITS_TIMEZONE = 11
DATETIME_MONTH_MULTIPLICATOR = 32
DATETIME_TIMEZONE_OFFSET_IN_MINUTES = 896
UINT_MAX_VALUE = 65535
FLOAT_EXPONENT_SPECIAL_VALUES = -16384
FLOAT_MANTISSA_INFINITY = 1
FLOAT_MANTISSA_MINUS_INFINITY = -1
FLOAT_MANTISSA_NOT_A_NUMBER = 0
EXI_MAXIMUM_NUMBER_OF_NAME_PARTITION_ENTRIES = 25
MAX_NUMBER_OF_RUNTIME_ELEMENTS = 80
EXI_EVENT_START_DOCUMENT = 0
EXI_EVENT_END_DOCUMENT = 0
EXI_EVENT_START_ELEMENT = 0
EXI_EVENT_START_ELEMENT_NS = 0
EXI_EVENT_START_ELEMENT_GENERIC = 0
EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED = 0
EXI_EVENT_END_ELEMENT = 0
EXI_EVENT_END_ELEMENT_UNDECLARED = 0
EXI_EVENT_CHARACTERS = 0
EXI_EVENT_CHARACTERS_GENERIC = 0
EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED = 0
EXI_EVENT_ATTRIBUTE_XSI_TYPE = 0
EXI_EVENT_ATTRIBUTE_XSI_NIL = 0
EXI_EVENT_ATTRIBUTE = 0
EXI_EVENT_ATTRIBUTE_NS = 0
EXI_EVENT_ATTRIBUTE_GENERIC = 0
EXI_EVENT_ATTRIBUTE_INVALID_VALUE = 0
EXI_EVENT_ATTRIBUTE_ANY_INVALID_VALUE = 0
EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED = 0
EXI_EVENT_ERROR = 0
EXI_DATATYPE_BINARY_BASE64 = 0
EXI_DATATYPE_BINARY_HEX = 0
EXI_DATATYPE_BOOLEAN = 0
EXI_DATATYPE_BOOLEAN_FACET = 0
EXI_DATATYPE_DECIMAL = 0
EXI_DATATYPE_FLOAT = 0
EXI_DATATYPE_NBIT_UNSIGNED_INTEGER = 0
EXI_DATATYPE_UNSIGNED_INTEGER = 0
EXI_DATATYPE_INTEGER = 0
EXI_DATATYPE_DATETIME = 0
EXI_DATATYPE_STRING = 0
EXI_DATATYPE_RCS_STRING = 0
EXI_DATATYPE_ENUMERATION = 0
EXI_DATATYPE_LIST = 0
EXI_DATATYPE_QNAME = 0
EXI_UNSIGNED_INTEGER_8 = 0
EXI_UNSIGNED_INTEGER_16 = 0
EXI_UNSIGNED_INTEGER_32 = 0
EXI_UNSIGNED_INTEGER_64 = 0
EXI_INTEGER_8 = 0
EXI_INTEGER_16 = 0
EXI_INTEGER_32 = 0
EXI_INTEGER_64 = 0
EXI_DATETIME_GYEAR = 0
EXI_DATETIME_GYEARMONTH = 0
EXI_DATETIME_DATE = 0
EXI_DATETIME_DATETIME = 0
EXI_DATETIME_GMONTH = 0
EXI_DATETIME_GMONTHDAY = 0
EXI_DATETIME_GDAY = 0
EXI_DATETIME_TIME = 0
EXI_STRING_VALUE_MISS = 0
EXI_STRING_VALUE_LOCAL_HIT = 0
EXI_STRING_VALUE_GLOBAL_HIT = 0
EXI_NAME_ENTRY_TYPE_ID = 0
EXI_NAME_ENTRY_TYPE_STRING_AND_ID = 0
EXI_NAME_PARTITION_URI = 0
EXI_NAME_PARTITION_LOCALNAME = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
BIT_PACKED = 1
BYTE_ALIGNMENT = 2
EXI_OPTION_ALIGNMENT = BIT_PACKED
EXI_OPTION_STRICT = 0
EXI_OPTION_VALUE_MAX_LENGTH = -1
EXI_OPTION_VALUE_PARTITION_CAPACITY = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
MAX_OCTETS_FOR_UNSIGNED_INTEGER_64 = 10
MAX_OCTETS_FOR_UNSIGNED_INTEGER_32 = 5
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
SUPPORT_YES = 1
SUPPORT_NO = 2
DEPLOY_ISO1_CODEC = SUPPORT_YES
DEPLOY_ISO1_CODEC_FRAGMENT = SUPPORT_YES
UNION_YES = 1
UNION_NO = 2
SAVE_MEMORY_WITH_UNNAMED_UNION = UNION_YES
iso1DiffieHellmanPublickeyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1DiffieHellmanPublickeyType_CONTENT_BYTES_SIZE = 350
iso1EMAIDType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1EMAIDType_CONTENT_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1AuthorizationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1AuthorizationReqType_GenChallenge_BYTES_SIZE = 16
iso1MeterInfoType_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso1MeterInfoType_SigMeterReading_BYTES_SIZE = 64
iso1ObjectType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ObjectType_MimeType_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ObjectType_Encoding_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ObjectType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1RSAKeyValueType_Modulus_BYTES_SIZE = 350
iso1RSAKeyValueType_Exponent_BYTES_SIZE = 350
iso1SignatureValueType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignatureValueType_CONTENT_BYTES_SIZE = 350
iso1SubCertificatesType_Certificate_BYTES_SIZE = 800
iso1SubCertificatesType_Certificate_ARRAY_SIZE = 4
iso1DSAKeyValueType_P_BYTES_SIZE = 350
iso1DSAKeyValueType_Q_BYTES_SIZE = 350
iso1DSAKeyValueType_G_BYTES_SIZE = 350
iso1DSAKeyValueType_Y_BYTES_SIZE = 350
iso1DSAKeyValueType_J_BYTES_SIZE = 350
iso1DSAKeyValueType_Seed_BYTES_SIZE = 350
iso1DSAKeyValueType_PgenCounter_BYTES_SIZE = 350
iso1MeteringReceiptReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1MeteringReceiptReqType_SessionID_BYTES_SIZE = 8
iso1KeyValueType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1X509IssuerSerialType_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignatureMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso1SignatureMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1X509DataType_X509IssuerSerial_ARRAY_SIZE = 1
iso1X509DataType_X509SKI_BYTES_SIZE = 350
iso1X509DataType_X509SKI_ARRAY_SIZE = 1
iso1X509DataType_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1X509DataType_X509SubjectName_ARRAY_SIZE = 1
iso1X509DataType_X509Certificate_BYTES_SIZE = 350
iso1X509DataType_X509Certificate_ARRAY_SIZE = 1
iso1X509DataType_X509CRL_BYTES_SIZE = 350
iso1X509DataType_X509CRL_ARRAY_SIZE = 1
iso1X509DataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1NotificationType_FaultMsg_CHARACTERS_SIZE = 64 + EXTRA_CHAR
iso1TransformType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso1TransformType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1TransformType_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1TransformType_XPath_ARRAY_SIZE = 1
iso1PaymentDetailsResType_GenChallenge_BYTES_SIZE = 16
iso1ContractSignatureEncryptedPrivateKeyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ContractSignatureEncryptedPrivateKeyType_CONTENT_BYTES_SIZE = 350
iso1SPKIDataType_SPKISexp_BYTES_SIZE = 350
iso1SPKIDataType_SPKISexp_ARRAY_SIZE = 1
iso1SPKIDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SessionSetupReqType_EVCCID_BYTES_SIZE = 6
iso1CanonicalizationMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso1CanonicalizationMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ServiceType_ServiceName_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso1ServiceType_ServiceScope_CHARACTERS_SIZE = 64 + EXTRA_CHAR
iso1ServiceDiscoveryReqType_ServiceScope_CHARACTERS_SIZE = 64 + EXTRA_CHAR
iso1SupportedEnergyTransferModeType_EnergyTransferMode_ARRAY_SIZE = 6
iso1DigestMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
iso1DigestMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignaturePropertyType_Target_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignaturePropertyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignaturePropertyType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1PGPDataType_PGPKeyID_BYTES_SIZE = 350
iso1PGPDataType_PGPKeyPacket_BYTES_SIZE = 350
iso1PGPDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SessionSetupResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso1CertificateChainType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1CertificateChainType_Certificate_BYTES_SIZE = 800
iso1ServiceListType_Service_ARRAY_SIZE = 8
iso1PaymentOptionListType_PaymentOption_ARRAY_SIZE = 2
iso1PaymentDetailsReqType_eMAID_CHARACTERS_SIZE = 15 + EXTRA_CHAR
iso1ChargingStatusResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso1ListOfRootCertificateIDsType_RootCertificateID_ARRAY_SIZE = 5
iso1ChargeServiceType_ServiceName_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso1ChargeServiceType_ServiceScope_CHARACTERS_SIZE = 64 + EXTRA_CHAR
iso1SelectedServiceListType_SelectedService_ARRAY_SIZE = 16
iso1TransformsType_Transform_ARRAY_SIZE = 1
iso1ReferenceType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ReferenceType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ReferenceType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ReferenceType_DigestValue_BYTES_SIZE = 350
iso1RetrievalMethodType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1RetrievalMethodType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1CurrentDemandResType_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
iso1SignaturePropertiesType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignaturePropertiesType_SignatureProperty_ARRAY_SIZE = 1
iso1ParameterType_Name_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ParameterType_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1CertificateInstallationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1CertificateInstallationReqType_OEMProvisioningCert_BYTES_SIZE = 800
iso1ParameterSetType_Parameter_ARRAY_SIZE = 16
iso1SignedInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignedInfoType_Reference_ARRAY_SIZE = 1
iso1ManifestType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ManifestType_Reference_ARRAY_SIZE = 1
iso1ConsumptionCostType_Cost_ARRAY_SIZE = 3
iso1PMaxScheduleType_PMaxScheduleEntry_ARRAY_SIZE = 5
iso1CertificateUpdateReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1CertificateUpdateReqType_eMAID_CHARACTERS_SIZE = 15 + EXTRA_CHAR
iso1KeyInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1KeyInfoType_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1KeyInfoType_KeyName_ARRAY_SIZE = 1
iso1KeyInfoType_KeyValue_ARRAY_SIZE = 1
iso1KeyInfoType_RetrievalMethod_ARRAY_SIZE = 1
iso1KeyInfoType_X509Data_ARRAY_SIZE = 1
iso1KeyInfoType_PGPData_ARRAY_SIZE = 1
iso1KeyInfoType_SPKIData_ARRAY_SIZE = 1
iso1KeyInfoType_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1KeyInfoType_MgmtData_ARRAY_SIZE = 1
iso1KeyInfoType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1ChargingProfileType_ProfileEntry_ARRAY_SIZE = 24
iso1SalesTariffEntryType_ConsumptionCost_ARRAY_SIZE = 3
iso1SalesTariffType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SalesTariffType_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
iso1SalesTariffType_SalesTariffEntry_ARRAY_SIZE = 5
iso1SignatureType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1SignatureType_Object_ARRAY_SIZE = 1
iso1ServiceParameterListType_ParameterSet_ARRAY_SIZE = 5
iso1MessageHeaderType_SessionID_BYTES_SIZE = 8
iso1SAScheduleListType_SAScheduleTuple_ARRAY_SIZE = 3
EXIDocument_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_DigestValue_BYTES_SIZE = 350
EXIFragment_Exponent_BYTES_SIZE = 350
EXIFragment_PgenCounter_BYTES_SIZE = 350
EXIFragment_SessionID_BYTES_SIZE = 8
EXIFragment_PGPKeyPacket_BYTES_SIZE = 350
EXIFragment_Seed_BYTES_SIZE = 350
EXIFragment_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_OEMProvisioningCert_BYTES_SIZE = 800
EXIFragment_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_EVCCID_BYTES_SIZE = 6
EXIFragment_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_P_BYTES_SIZE = 350
EXIFragment_Q_BYTES_SIZE = 350
EXIFragment_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_G_BYTES_SIZE = 350
EXIFragment_J_BYTES_SIZE = 350
EXIFragment_ServiceScope_CHARACTERS_SIZE = 64 + EXTRA_CHAR
EXIFragment_ServiceName_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_X509CRL_BYTES_SIZE = 350
EXIFragment_Y_BYTES_SIZE = 350
EXIFragment_DigestValue_BYTES_SIZE = 350
EXIFragment_SPKISexp_BYTES_SIZE = 350
EXIFragment_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_PGPKeyID_BYTES_SIZE = 350
EXIFragment_X509Certificate_BYTES_SIZE = 350
EXIFragment_FaultMsg_CHARACTERS_SIZE = 64 + EXTRA_CHAR
EXIFragment_EVSEID_CHARACTERS_SIZE = 37 + EXTRA_CHAR
EXIFragment_SigMeterReading_BYTES_SIZE = 64
EXIFragment_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_GenChallenge_BYTES_SIZE = 16
EXIFragment_X509SKI_BYTES_SIZE = 350
EXIFragment_Certificate_BYTES_SIZE = 800
EXIFragment_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_Modulus_BYTES_SIZE = 350
exiElementFrag_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
exiElementFrag_CHARACTERS_GENERIC_CHARACTERS_SIZE = 50 + EXTRA_CHAR
iso1DC_EVErrorCodeType_NO_ERROR = 0
iso1DC_EVErrorCodeType_FAILED_RESSTemperatureInhibit = 1
iso1DC_EVErrorCodeType_FAILED_EVShiftPosition = 2
iso1DC_EVErrorCodeType_FAILED_ChargerConnectorLockFault = 3
iso1DC_EVErrorCodeType_FAILED_EVRESSMalfunction = 4
iso1DC_EVErrorCodeType_FAILED_ChargingCurrentdifferential = 5
iso1DC_EVErrorCodeType_FAILED_ChargingVoltageOutOfRange = 6
iso1DC_EVErrorCodeType_Reserved_A = 7
iso1DC_EVErrorCodeType_Reserved_B = 8
iso1DC_EVErrorCodeType_Reserved_C = 9
iso1DC_EVErrorCodeType_FAILED_ChargingSystemIncompatibility = 10
iso1DC_EVErrorCodeType_NoData = 11
iso1EVSENotificationType_None = 0
iso1EVSENotificationType_StopCharging = 1
iso1EVSENotificationType_ReNegotiation = 2
iso1responseCodeType_OK = 0
iso1responseCodeType_OK_NewSessionEstablished = 1
iso1responseCodeType_OK_OldSessionJoined = 2
iso1responseCodeType_OK_CertificateExpiresSoon = 3
iso1responseCodeType_FAILED = 4
iso1responseCodeType_FAILED_SequenceError = 5
iso1responseCodeType_FAILED_ServiceIDInvalid = 6
iso1responseCodeType_FAILED_UnknownSession = 7
iso1responseCodeType_FAILED_ServiceSelectionInvalid = 8
iso1responseCodeType_FAILED_PaymentSelectionInvalid = 9
iso1responseCodeType_FAILED_CertificateExpired = 10
iso1responseCodeType_FAILED_SignatureError = 11
iso1responseCodeType_FAILED_NoCertificateAvailable = 12
iso1responseCodeType_FAILED_CertChainError = 13
iso1responseCodeType_FAILED_ChallengeInvalid = 14
iso1responseCodeType_FAILED_ContractCanceled = 15
iso1responseCodeType_FAILED_WrongChargeParameter = 16
iso1responseCodeType_FAILED_PowerDeliveryNotApplied = 17
iso1responseCodeType_FAILED_TariffSelectionInvalid = 18
iso1responseCodeType_FAILED_ChargingProfileInvalid = 19
iso1responseCodeType_FAILED_MeteringSignatureNotValid = 20
iso1responseCodeType_FAILED_NoChargeServiceSelected = 21
iso1responseCodeType_FAILED_WrongEnergyTransferMode = 22
iso1responseCodeType_FAILED_ContactorError = 23
iso1responseCodeType_FAILED_CertificateNotAllowedAtThisEVSE = 24
iso1responseCodeType_FAILED_CertificateRevoked = 25
iso1faultCodeType_ParsingError = 0
iso1faultCodeType_NoTLSRootCertificatAvailable = 1
iso1faultCodeType_UnknownError = 2
iso1DC_EVSEStatusCodeType_EVSE_NotReady = 0
iso1DC_EVSEStatusCodeType_EVSE_Ready = 1
iso1DC_EVSEStatusCodeType_EVSE_Shutdown = 2
iso1DC_EVSEStatusCodeType_EVSE_UtilityInterruptEvent = 3
iso1DC_EVSEStatusCodeType_EVSE_IsolationMonitoringActive = 4
iso1DC_EVSEStatusCodeType_EVSE_EmergencyShutdown = 5
iso1DC_EVSEStatusCodeType_EVSE_Malfunction = 6
iso1DC_EVSEStatusCodeType_Reserved_8 = 7
iso1DC_EVSEStatusCodeType_Reserved_9 = 8
iso1DC_EVSEStatusCodeType_Reserved_A = 9
iso1DC_EVSEStatusCodeType_Reserved_B = 10
iso1DC_EVSEStatusCodeType_Reserved_C = 11
iso1EVSEProcessingType_Finished = 0
iso1EVSEProcessingType_Ongoing = 1
iso1EVSEProcessingType_Ongoing_WaitingForCustomerInteraction = 2
iso1chargingSessionType_Terminate = 0
iso1chargingSessionType_Pause = 1
iso1serviceCategoryType_EVCharging = 0
iso1serviceCategoryType_Internet = 1
iso1serviceCategoryType_ContractCertificate = 2
iso1serviceCategoryType_OtherCustom = 3
iso1paymentOptionType_Contract = 0
iso1paymentOptionType_ExternalPayment = 1
iso1EnergyTransferModeType_AC_single_phase_core = 0
iso1EnergyTransferModeType_AC_three_phase_core = 1
iso1EnergyTransferModeType_DC_core = 2
iso1EnergyTransferModeType_DC_extended = 3
iso1EnergyTransferModeType_DC_combo_core = 4
iso1EnergyTransferModeType_DC_unique = 5
iso1isolationLevelType_Invalid = 0
iso1isolationLevelType_Valid = 1
iso1isolationLevelType_Warning = 2
iso1isolationLevelType_Fault = 3
iso1isolationLevelType_No_IMD = 4
iso1costKindType_relativePricePercentage = 0
iso1costKindType_RenewableGenerationPercentage = 1
iso1costKindType_CarbonDioxideEmission = 2
iso1chargeProgressType_Start = 0
iso1chargeProgressType_Stop = 1
iso1chargeProgressType_Renegotiate = 2
iso1valueType_bool = 0
iso1valueType_byte = 1
iso1valueType_short = 2
iso1valueType_int = 3
iso1valueType_physicalValue = 4
iso1valueType_string = 5
iso1unitSymbolType_h = 0
iso1unitSymbolType_m = 1
iso1unitSymbolType_s = 2
iso1unitSymbolType_A = 3
iso1unitSymbolType_V = 4
iso1unitSymbolType_W = 5
iso1unitSymbolType_Wh = 6
EXTRA_CHAR = 0
UNION_YES = 1
UNION_NO = 2
SAVE_MEMORY_WITH_UNNAMED_UNION = UNION_YES
appHandAppProtocolType_ProtocolNamespace_CHARACTERS_SIZE = 100
appHandAnonType_supportedAppProtocolReq_AppProtocol_ARRAY_SIZE = 5
appHandresponseCodeType_OK_SuccessfulNegotiation = 0
appHandresponseCodeType_OK_SuccessfulNegotiationWithMinorDeviation = 1
appHandresponseCodeType_Failed_NoNegotiation = 2
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
EXTRA_CHAR = 0
SUPPORT_YES = 1
SUPPORT_NO = 2
DEPLOY_DIN_CODEC = SUPPORT_YES
DEPLOY_DIN_CODEC_FRAGMENT = SUPPORT_NO
UNION_YES = 1
UNION_NO = 2
SAVE_MEMORY_WITH_UNNAMED_UNION = UNION_YES
dinSessionSetupReqType_EVCCID_BYTES_SIZE = 8
dinCanonicalizationMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
dinCanonicalizationMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSPKIDataType_SPKISexp_BYTES_SIZE = 350
dinSPKIDataType_SPKISexp_ARRAY_SIZE = 1
dinSPKIDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinListOfRootCertificateIDsType_RootCertificateID_CHARACTERS_SIZE = 40 + EXTRA_CHAR
dinListOfRootCertificateIDsType_RootCertificateID_ARRAY_SIZE = 5
dinTransformType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
dinTransformType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinTransformType_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinTransformType_XPath_ARRAY_SIZE = 1
dinContractAuthenticationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinContractAuthenticationReqType_GenChallenge_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinDSAKeyValueType_P_BYTES_SIZE = 350
dinDSAKeyValueType_Q_BYTES_SIZE = 350
dinDSAKeyValueType_G_BYTES_SIZE = 350
dinDSAKeyValueType_Y_BYTES_SIZE = 350
dinDSAKeyValueType_J_BYTES_SIZE = 350
dinDSAKeyValueType_Seed_BYTES_SIZE = 350
dinDSAKeyValueType_PgenCounter_BYTES_SIZE = 350
dinTransformsType_Transform_ARRAY_SIZE = 1
dinDigestMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
dinDigestMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignatureMethodType_Algorithm_CHARACTERS_SIZE = 65 + EXTRA_CHAR
dinSignatureMethodType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateInstallationReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateInstallationReqType_OEMProvisioningCert_BYTES_SIZE = 1200
dinCertificateInstallationReqType_DHParams_BYTES_SIZE = 256
dinReferenceType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinReferenceType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinReferenceType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinReferenceType_DigestValue_BYTES_SIZE = 350
dinRSAKeyValueType_Modulus_BYTES_SIZE = 350
dinRSAKeyValueType_Exponent_BYTES_SIZE = 350
dinX509IssuerSerialType_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinManifestType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinManifestType_Reference_ARRAY_SIZE = 1
dinSignatureValueType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignatureValueType_CONTENT_BYTES_SIZE = 350
dinPaymentOptionsType_PaymentOption_ARRAY_SIZE = 5
dinServiceTagType_ServiceName_CHARACTERS_SIZE = 32 + EXTRA_CHAR
dinServiceTagType_ServiceScope_CHARACTERS_SIZE = 32 + EXTRA_CHAR
dinChargingProfileType_ProfileEntry_ARRAY_SIZE = 24
dinServiceDiscoveryReqType_ServiceScope_CHARACTERS_SIZE = 32 + EXTRA_CHAR
dinObjectType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinObjectType_MimeType_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinObjectType_Encoding_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinObjectType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignedInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignedInfoType_Reference_ARRAY_SIZE = 1
dinRetrievalMethodType_URI_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinRetrievalMethodType_Type_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinNotificationType_FaultMsg_CHARACTERS_SIZE = 64 + EXTRA_CHAR
dinPGPDataType_PGPKeyID_BYTES_SIZE = 350
dinPGPDataType_PGPKeyPacket_BYTES_SIZE = 350
dinPGPDataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignaturePropertyType_Target_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignaturePropertyType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignaturePropertyType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinMeterInfoType_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
dinMeterInfoType_SigMeterReading_BYTES_SIZE = 32
dinSubCertificatesType_Certificate_BYTES_SIZE = 1200
dinSubCertificatesType_Certificate_ARRAY_SIZE = 5
dinMeteringReceiptReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinMeteringReceiptReqType_SessionID_BYTES_SIZE = 8
dinSelectedServiceListType_SelectedService_ARRAY_SIZE = 16
dinX509DataType_X509IssuerSerial_ARRAY_SIZE = 1
dinX509DataType_X509SKI_BYTES_SIZE = 350
dinX509DataType_X509SKI_ARRAY_SIZE = 1
dinX509DataType_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinX509DataType_X509SubjectName_ARRAY_SIZE = 1
dinX509DataType_X509Certificate_BYTES_SIZE = 350
dinX509DataType_X509Certificate_ARRAY_SIZE = 1
dinX509DataType_X509CRL_BYTES_SIZE = 350
dinX509DataType_X509CRL_ARRAY_SIZE = 1
dinX509DataType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinChargingStatusResType_EVSEID_BYTES_SIZE = 32
dinSignaturePropertiesType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignaturePropertiesType_SignatureProperty_ARRAY_SIZE = 1
dinPMaxScheduleType_PMaxScheduleEntry_ARRAY_SIZE = 5
dinPaymentDetailsResType_GenChallenge_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinKeyValueType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateChainType_Certificate_BYTES_SIZE = 1200
dinParameterType_Name_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinParameterType_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinParameterSetType_Parameter_ARRAY_SIZE = 16
dinConsumptionCostType_Cost_ARRAY_SIZE = 5
dinServiceTagListType_Service_ARRAY_SIZE = 8
dinSessionSetupResType_EVSEID_BYTES_SIZE = 32
dinServiceParameterListType_ParameterSet_ARRAY_SIZE = 5
dinCertificateUpdateReqType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateUpdateReqType_ContractID_CHARACTERS_SIZE = 24 + EXTRA_CHAR
dinCertificateUpdateReqType_DHParams_BYTES_SIZE = 256
dinKeyInfoType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinKeyInfoType_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinKeyInfoType_KeyName_ARRAY_SIZE = 1
dinKeyInfoType_KeyValue_ARRAY_SIZE = 1
dinKeyInfoType_RetrievalMethod_ARRAY_SIZE = 1
dinKeyInfoType_X509Data_ARRAY_SIZE = 1
dinKeyInfoType_PGPData_ARRAY_SIZE = 1
dinKeyInfoType_SPKIData_ARRAY_SIZE = 1
dinKeyInfoType_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinKeyInfoType_MgmtData_ARRAY_SIZE = 1
dinKeyInfoType_ANY_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinPaymentDetailsReqType_ContractID_CHARACTERS_SIZE = 24 + EXTRA_CHAR
dinCertificateInstallationResType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateInstallationResType_ContractSignatureEncryptedPrivateKey_BYTES_SIZE = 128
dinCertificateInstallationResType_DHParams_BYTES_SIZE = 256
dinCertificateInstallationResType_ContractID_CHARACTERS_SIZE = 24 + EXTRA_CHAR
dinCertificateUpdateResType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinCertificateUpdateResType_ContractSignatureEncryptedPrivateKey_BYTES_SIZE = 128
dinCertificateUpdateResType_DHParams_BYTES_SIZE = 256
dinCertificateUpdateResType_ContractID_CHARACTERS_SIZE = 24 + EXTRA_CHAR
dinSalesTariffEntryType_ConsumptionCost_ARRAY_SIZE = 5
dinSignatureType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSignatureType_Object_ARRAY_SIZE = 1
dinSalesTariffType_Id_CHARACTERS_SIZE = 50 + EXTRA_CHAR
dinSalesTariffType_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
dinSalesTariffType_SalesTariffEntry_ARRAY_SIZE = 5
dinMessageHeaderType_SessionID_BYTES_SIZE = 8
dinSAScheduleListType_SAScheduleTuple_ARRAY_SIZE = 5
EXIDocument_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIDocument_DigestValue_BYTES_SIZE = 350
EXIFragment_Certificate_BYTES_SIZE = 1200
EXIFragment_stringValue_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_OEMProvisioningCert_BYTES_SIZE = 1200
EXIFragment_Exponent_BYTES_SIZE = 350
EXIFragment_SessionID_BYTES_SIZE = 8
EXIFragment_PgenCounter_BYTES_SIZE = 350
EXIFragment_EVCCID_BYTES_SIZE = 8
EXIFragment_RootCertificateID_CHARACTERS_SIZE = 40 + EXTRA_CHAR
EXIFragment_PGPKeyPacket_BYTES_SIZE = 350
EXIFragment_Seed_BYTES_SIZE = 350
EXIFragment_XPath_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_ContractID_CHARACTERS_SIZE = 24 + EXTRA_CHAR
EXIFragment_MgmtData_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_P_BYTES_SIZE = 350
EXIFragment_Q_BYTES_SIZE = 350
EXIFragment_X509SubjectName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_G_BYTES_SIZE = 350
EXIFragment_J_BYTES_SIZE = 350
EXIFragment_X509CRL_BYTES_SIZE = 350
EXIFragment_Y_BYTES_SIZE = 350
EXIFragment_DigestValue_BYTES_SIZE = 350
EXIFragment_ContractSignatureEncryptedPrivateKey_BYTES_SIZE = 128
EXIFragment_SPKISexp_BYTES_SIZE = 350
EXIFragment_DHParams_BYTES_SIZE = 256
EXIFragment_PGPKeyID_BYTES_SIZE = 350
EXIFragment_X509Certificate_BYTES_SIZE = 350
EXIFragment_ServiceName_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_EVSEID_BYTES_SIZE = 32
EXIFragment_ServiceScope_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_GenChallenge_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_SalesTariffDescription_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_FaultMsg_CHARACTERS_SIZE = 64 + EXTRA_CHAR
EXIFragment_KeyName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_SigMeterReading_BYTES_SIZE = 32
EXIFragment_X509SKI_BYTES_SIZE = 350
EXIFragment_X509IssuerName_CHARACTERS_SIZE = 50 + EXTRA_CHAR
EXIFragment_MeterID_CHARACTERS_SIZE = 32 + EXTRA_CHAR
EXIFragment_Modulus_BYTES_SIZE = 350
dinEVSEProcessingType_Finished = 0
dinEVSEProcessingType_Ongoing = 1
dinDC_EVErrorCodeType_NO_ERROR = 0
dinDC_EVErrorCodeType_FAILED_RESSTemperatureInhibit = 1
dinDC_EVErrorCodeType_FAILED_EVShiftPosition = 2
dinDC_EVErrorCodeType_FAILED_ChargerConnectorLockFault = 3
dinDC_EVErrorCodeType_FAILED_EVRESSMalfunction = 4
dinDC_EVErrorCodeType_FAILED_ChargingCurrentdifferential = 5
dinDC_EVErrorCodeType_FAILED_ChargingVoltageOutOfRange = 6
dinDC_EVErrorCodeType_Reserved_A = 7
dinDC_EVErrorCodeType_Reserved_B = 8
dinDC_EVErrorCodeType_Reserved_C = 9
dinDC_EVErrorCodeType_FAILED_ChargingSystemIncompatibility = 10
dinDC_EVErrorCodeType_NoData = 11
dinunitSymbolType_h = 0
dinunitSymbolType_m = 1
dinunitSymbolType_s = 2
dinunitSymbolType_A = 3
dinunitSymbolType_Ah = 4
dinunitSymbolType_V = 5
dinunitSymbolType_VA = 6
dinunitSymbolType_W = 7
dinunitSymbolType_W_s = 8
dinunitSymbolType_Wh = 9
dinvalueType_bool = 0
dinvalueType_byte = 1
dinvalueType_short = 2
dinvalueType_int = 3
dinvalueType_physicalValue = 4
dinvalueType_string = 5
dinEVRequestedEnergyTransferType_AC_single_phase_core = 0
dinEVRequestedEnergyTransferType_AC_three_phase_core = 1
dinEVRequestedEnergyTransferType_DC_core = 2
dinEVRequestedEnergyTransferType_DC_extended = 3
dinEVRequestedEnergyTransferType_DC_combo_core = 4
dinEVRequestedEnergyTransferType_DC_unique = 5
dinpaymentOptionType_Contract = 0
dinpaymentOptionType_ExternalPayment = 1
dinEVSESupportedEnergyTransferType_AC_single_phase_core = 0
dinEVSESupportedEnergyTransferType_AC_three_phase_core = 1
dinEVSESupportedEnergyTransferType_DC_core = 2
dinEVSESupportedEnergyTransferType_DC_extended = 3
dinEVSESupportedEnergyTransferType_DC_combo_core = 4
dinEVSESupportedEnergyTransferType_DC_dual = 5
dinEVSESupportedEnergyTransferType_AC_core1p_DC_extended = 6
dinEVSESupportedEnergyTransferType_AC_single_DC_core = 7
dinEVSESupportedEnergyTransferType_AC_single_phase_three_phase_core_DC_extended = 8
dinEVSESupportedEnergyTransferType_AC_core3p_DC_extended = 9
dinfaultCodeType_ParsingError = 0
dinfaultCodeType_NoTLSRootCertificatAvailable = 1
dinfaultCodeType_UnknownError = 2
dinserviceCategoryType_EVCharging = 0
dinserviceCategoryType_Internet = 1
dinserviceCategoryType_ContractCertificate = 2
dinserviceCategoryType_OtherCustom = 3
dinEVSENotificationType_None = 0
dinEVSENotificationType_StopCharging = 1
dinEVSENotificationType_ReNegotiation = 2
dincostKindType_relativePricePercentage = 0
dincostKindType_RenewableGenerationPercentage = 1
dincostKindType_CarbonDioxideEmission = 2
dinisolationLevelType_Invalid = 0
dinisolationLevelType_Valid = 1
dinisolationLevelType_Warning = 2
dinisolationLevelType_Fault = 3
dinresponseCodeType_OK = 0
dinresponseCodeType_OK_NewSessionEstablished = 1
dinresponseCodeType_OK_OldSessionJoined = 2
dinresponseCodeType_OK_CertificateExpiresSoon = 3
dinresponseCodeType_FAILED = 4
dinresponseCodeType_FAILED_SequenceError = 5
dinresponseCodeType_FAILED_ServiceIDInvalid = 6
dinresponseCodeType_FAILED_UnknownSession = 7
dinresponseCodeType_FAILED_ServiceSelectionInvalid = 8
dinresponseCodeType_FAILED_PaymentSelectionInvalid = 9
dinresponseCodeType_FAILED_CertificateExpired = 10
dinresponseCodeType_FAILED_SignatureError = 11
dinresponseCodeType_FAILED_NoCertificateAvailable = 12
dinresponseCodeType_FAILED_CertChainError = 13
dinresponseCodeType_FAILED_ChallengeInvalid = 14
dinresponseCodeType_FAILED_ContractCanceled = 15
dinresponseCodeType_FAILED_WrongChargeParameter = 16
dinresponseCodeType_FAILED_PowerDeliveryNotApplied = 17
dinresponseCodeType_FAILED_TariffSelectionInvalid = 18
dinresponseCodeType_FAILED_ChargingProfileInvalid = 19
dinresponseCodeType_FAILED_EVSEPresentVoltageToLow = 20
dinresponseCodeType_FAILED_MeteringSignatureNotValid = 21
dinresponseCodeType_FAILED_WrongEnergyTransferType = 22
EXTRA_CHAR = 0
dinDC_EVSEStatusCodeType_EVSE_NotReady = 0
dinDC_EVSEStatusCodeType_EVSE_Ready = 1
dinDC_EVSEStatusCodeType_EVSE_Shutdown = 2
dinDC_EVSEStatusCodeType_EVSE_UtilityInterruptEvent = 3
dinDC_EVSEStatusCodeType_EVSE_IsolationMonitoringActive = 4
dinDC_EVSEStatusCodeType_EVSE_EmergencyShutdown = 5
dinDC_EVSEStatusCodeType_EVSE_Malfunction = 6
dinDC_EVSEStatusCodeType_Reserved_8 = 7
dinDC_EVSEStatusCodeType_Reserved_9 = 8
dinDC_EVSEStatusCodeType_Reserved_A = 9
dinDC_EVSEStatusCodeType_Reserved_B = 10
dinDC_EVSEStatusCodeType_Reserved_C = 11

exi_string_character_t = c_uint32
exi_datetime_type_t = c_uint32
