/*
 * Copyright (C) 2007-2018 Siemens AG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 0.9.4 
 * @contact Richard.Kuntschke@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: V2G_CI_MsgDef.xsd</p>
 *
 *
 ********************************************************************/



#include <stdint.h>
#include <stddef.h>


#include "dinEXIDatatypes.h"
#include "../codec/EXITypes.h"


#ifndef EXI_din_DATATYPES_C
#define EXI_din_DATATYPES_C

#if DEPLOY_DIN_CODEC == SUPPORT_YES


void init_dinEXIDocument(struct dinEXIDocument* exiDoc) {
	// printf("[C] sizeof dinEXIDocument = %ld\n", sizeof(struct dinEXIDocument));
	// printf("[C] datetimenow = %ld\n", exiDoc->SessionSetupRes.DateTimeNow);
	// validated
	exiDoc->BodyElement_isUsed = 0u;
	exiDoc->V2G_Message_isUsed = 0u;
	exiDoc->SignatureProperty_isUsed = 0u;
	exiDoc->DSAKeyValue_isUsed = 0u;
	exiDoc->SignatureProperties_isUsed = 0u;
	exiDoc->KeyValue_isUsed = 0u;
	exiDoc->Transforms_isUsed = 0u;
	exiDoc->DigestMethod_isUsed = 0u;
	exiDoc->Signature_isUsed = 0u;
	exiDoc->RetrievalMethod_isUsed = 0u;
	exiDoc->Manifest_isUsed = 0u;
	exiDoc->Reference_isUsed = 0u;
	exiDoc->CanonicalizationMethod_isUsed = 0u;
	exiDoc->RSAKeyValue_isUsed = 0u;
	exiDoc->Transform_isUsed = 0u;
	exiDoc->PGPData_isUsed = 0u;
	exiDoc->MgmtData_isUsed = 0u;
	exiDoc->SignatureMethod_isUsed = 0u;
	exiDoc->KeyInfo_isUsed = 0u;
	exiDoc->SPKIData_isUsed = 0u;
	exiDoc->X509Data_isUsed = 0u;
	exiDoc->SignatureValue_isUsed = 0u;
	exiDoc->KeyName_isUsed = 0u;
	exiDoc->DigestValue_isUsed = 0u;
	exiDoc->SignedInfo_isUsed = 0u;
	exiDoc->Object_isUsed = 0u;
	exiDoc->DC_EVSEStatus_isUsed = 0u;
	exiDoc->RelativeTimeInterval_isUsed = 0u;
	exiDoc->SalesTariffEntry_isUsed = 0u;
	exiDoc->DC_EVPowerDeliveryParameter_isUsed = 0u;
	exiDoc->SASchedules_isUsed = 0u;
	exiDoc->AC_EVChargeParameter_isUsed = 0u;
	exiDoc->SAScheduleList_isUsed = 0u;
	exiDoc->DC_EVStatus_isUsed = 0u;
	exiDoc->ServiceCharge_isUsed = 0u;
	exiDoc->EVStatus_isUsed = 0u;
	exiDoc->DC_EVChargeParameter_isUsed = 0u;
	exiDoc->DC_EVSEChargeParameter_isUsed = 0u;
	exiDoc->EVSEStatus_isUsed = 0u;
	exiDoc->TimeInterval_isUsed = 0u;
	exiDoc->EVPowerDeliveryParameter_isUsed = 0u;
	exiDoc->EVSEChargeParameter_isUsed = 0u;
	exiDoc->AC_EVSEStatus_isUsed = 0u;
	exiDoc->Entry_isUsed = 0u;
	exiDoc->AC_EVSEChargeParameter_isUsed = 0u;
	exiDoc->PMaxScheduleEntry_isUsed = 0u;
	exiDoc->EVChargeParameter_isUsed = 0u;
	exiDoc->ServiceDiscoveryReq_isUsed = 0u;
	exiDoc->ServiceDiscoveryRes_isUsed = 0u;
	exiDoc->MeteringReceiptReq_isUsed = 0u;
	exiDoc->PaymentDetailsReq_isUsed = 0u;
	exiDoc->MeteringReceiptRes_isUsed = 0u;
	exiDoc->PaymentDetailsRes_isUsed = 0u;
	exiDoc->SessionSetupReq_isUsed = 0u;
	exiDoc->SessionSetupRes_isUsed = 0u;
	exiDoc->CableCheckReq_isUsed = 0u;
	exiDoc->CableCheckRes_isUsed = 0u;
	exiDoc->ContractAuthenticationReq_isUsed = 0u;
	exiDoc->CertificateInstallationReq_isUsed = 0u;
	exiDoc->ContractAuthenticationRes_isUsed = 0u;
	exiDoc->CertificateInstallationRes_isUsed = 0u;
	exiDoc->WeldingDetectionReq_isUsed = 0u;
	exiDoc->WeldingDetectionRes_isUsed = 0u;
	exiDoc->CertificateUpdateReq_isUsed = 0u;
	exiDoc->CertificateUpdateRes_isUsed = 0u;
	exiDoc->PowerDeliveryReq_isUsed = 0u;
	exiDoc->PowerDeliveryRes_isUsed = 0u;
	exiDoc->ChargingStatusReq_isUsed = 0u;
	exiDoc->ChargingStatusRes_isUsed = 0u;
	exiDoc->CurrentDemandReq_isUsed = 0u;
	exiDoc->PreChargeReq_isUsed = 0u;
	exiDoc->CurrentDemandRes_isUsed = 0u;
	exiDoc->PreChargeRes_isUsed = 0u;
	exiDoc->ServicePaymentSelectionReq_isUsed = 0u;
	exiDoc->SessionStopReq_isUsed = 0u;
	exiDoc->ServicePaymentSelectionRes_isUsed = 0u;
	exiDoc->SessionStopRes_isUsed = 0u;
	exiDoc->ChargeParameterDiscoveryReq_isUsed = 0u;
	exiDoc->ChargeParameterDiscoveryRes_isUsed = 0u;
	exiDoc->ServiceDetailReq_isUsed = 0u;
	exiDoc->ServiceDetailRes_isUsed = 0u;
}


#if DEPLOY_DIN_CODEC_FRAGMENT == SUPPORT_YES
void init_dinEXIFragment(struct dinEXIFragment* exiFrag) {
	exiFrag->Unit_isUsed = 0u;
	exiFrag->EVSEMaximumCurrentLimit_isUsed = 0u;
	exiFrag->EVPowerDeliveryParameter_isUsed = 0u;
	exiFrag->ChargingProfileEntryMaxPower_isUsed = 0u;
	exiFrag->TMeter_isUsed = 0u;
	exiFrag->EVSEPowerLimitAchieved_isUsed = 0u;
	exiFrag->duration_isUsed = 0u;
	exiFrag->EVMaximumCurrentLimit_isUsed = 0u;
	exiFrag->Parameter_isUsed = 0u;
	exiFrag->EVSEProcessing_isUsed = 0u;
	exiFrag->AC_EVChargeParameter_isUsed = 0u;
	exiFrag->EVSEProcessing_isUsed = 0u;
	exiFrag->PMaxScheduleEntry_isUsed = 0u;
	exiFrag->EVSEProcessing_isUsed = 0u;
	exiFrag->EVSEMaximumVoltageLimit_isUsed = 0u;
	exiFrag->SelectedService_isUsed = 0u;
	exiFrag->Certificate_isUsed = 0u;
	exiFrag->Certificate_isUsed = 0u;
	exiFrag->EVSEMaximumPowerLimit_isUsed = 0u;
	exiFrag->EVReady_isUsed = 0u;
	exiFrag->X509SerialNumber_isUsed = 0u;
	exiFrag->RetrievalMethod_isUsed = 0u;
	exiFrag->RetryCounter_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->MeteringReceiptReq_isUsed = 0u;
	exiFrag->ReadyToChargeState_isUsed = 0u;
	exiFrag->Multiplier_isUsed = 0u;
	exiFrag->EPriceLevel_isUsed = 0u;
	exiFrag->stringValue_isUsed = 0u;
	exiFrag->ServiceDiscoveryReq_isUsed = 0u;
	exiFrag->Transforms_isUsed = 0u;
	exiFrag->MeteringReceiptRes_isUsed = 0u;
	exiFrag->PreChargeReq_isUsed = 0u;
	exiFrag->OEMProvisioningCert_isUsed = 0u;
	exiFrag->ServiceDiscoveryRes_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ResponseCode_isUsed = 0u;
	exiFrag->ContractAuthenticationReq_isUsed = 0u;
	exiFrag->ContractSignatureCertChain_isUsed = 0u;
	exiFrag->ContractSignatureCertChain_isUsed = 0u;
	exiFrag->ContractSignatureCertChain_isUsed = 0u;
	exiFrag->ContractSignatureCertChain_isUsed = 0u;
	exiFrag->ContractAuthenticationRes_isUsed = 0u;
	exiFrag->HMACOutputLength_isUsed = 0u;
	exiFrag->BulkChargingComplete_isUsed = 0u;
	exiFrag->Exponent_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->SAScheduleTuple_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->DepartureTime_isUsed = 0u;
	exiFrag->X509IssuerSerial_isUsed = 0u;
	exiFrag->SAScheduleTupleID_isUsed = 0u;
	exiFrag->SAScheduleTupleID_isUsed = 0u;
	exiFrag->SPKIData_isUsed = 0u;
	exiFrag->RelativeTimeInterval_isUsed = 0u;
	exiFrag->EVEnergyRequest_isUsed = 0u;
	exiFrag->PreChargeRes_isUsed = 0u;
	exiFrag->SessionID_isUsed = 0u;
	exiFrag->PMaxSchedule_isUsed = 0u;
	exiFrag->ServiceCharge_isUsed = 0u;
	exiFrag->PgenCounter_isUsed = 0u;
	exiFrag->ChargingStatusReq_isUsed = 0u;
	exiFrag->X509Data_isUsed = 0u;
	exiFrag->SalesTariffEntry_isUsed = 0u;
	exiFrag->KeyValue_isUsed = 0u;
	exiFrag->ChargingStatusRes_isUsed = 0u;
	exiFrag->V2G_Message_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->ServicePaymentSelectionReq_isUsed = 0u;
	exiFrag->DC_EVStatus_isUsed = 0u;
	exiFrag->EVSEIsolationStatus_isUsed = 0u;
	exiFrag->ServicePaymentSelectionRes_isUsed = 0u;
	exiFrag->EVSEPresentVoltage_isUsed = 0u;
	exiFrag->EVSEPresentVoltage_isUsed = 0u;
	exiFrag->EVSEPresentVoltage_isUsed = 0u;
	exiFrag->BodyElement_isUsed = 0u;
	exiFrag->EVCCID_isUsed = 0u;
	exiFrag->PGPData_isUsed = 0u;
	exiFrag->RootCertificateID_isUsed = 0u;
	exiFrag->FaultCode_isUsed = 0u;
	exiFrag->CableCheckReq_isUsed = 0u;
	exiFrag->EVSEVoltageLimitAchieved_isUsed = 0u;
	exiFrag->EVRESSConditioning_isUsed = 0u;
	exiFrag->MeterInfo_isUsed = 0u;
	exiFrag->MeterInfo_isUsed = 0u;
	exiFrag->CableCheckRes_isUsed = 0u;
	exiFrag->ChargingProfileEntryStart_isUsed = 0u;
	exiFrag->SignatureProperty_isUsed = 0u;
	exiFrag->EVMaxCurrent_isUsed = 0u;
	exiFrag->PGPKeyPacket_isUsed = 0u;
	exiFrag->PGPKeyPacket_isUsed = 0u;
	exiFrag->Seed_isUsed = 0u;
	exiFrag->RSAKeyValue_isUsed = 0u;
	exiFrag->costKind_isUsed = 0u;
	exiFrag->EAmount_isUsed = 0u;
	exiFrag->EVSEPresentCurrent_isUsed = 0u;
	exiFrag->PowerDeliveryRes_isUsed = 0u;
	exiFrag->NumEPriceLevels_isUsed = 0u;
	exiFrag->SessionStopRes_isUsed = 0u;
	exiFrag->PowerDeliveryReq_isUsed = 0u;
	exiFrag->SessionStopReq_isUsed = 0u;
	exiFrag->XPath_isUsed = 0u;
	exiFrag->BulkSOC_isUsed = 0u;
	exiFrag->PMax_isUsed = 0u;
	exiFrag->ParameterSetID_isUsed = 0u;
	exiFrag->ParameterSetID_isUsed = 0u;
	exiFrag->ContractID_isUsed = 0u;
	exiFrag->ContractID_isUsed = 0u;
	exiFrag->ContractID_isUsed = 0u;
	exiFrag->ContractID_isUsed = 0u;
	exiFrag->Signature_isUsed = 0u;
	exiFrag->EVMaxVoltage_isUsed = 0u;
	exiFrag->ReceiptRequired_isUsed = 0u;
	exiFrag->ChargingComplete_isUsed = 0u;
	exiFrag->ChargingProfile_isUsed = 0u;
	exiFrag->PaymentOptions_isUsed = 0u;
	exiFrag->SessionSetupRes_isUsed = 0u;
	exiFrag->EVSEMaximumVoltageLimit_isUsed = 0u;
	exiFrag->ServiceDetailRes_isUsed = 0u;
	exiFrag->DC_EVPowerDeliveryParameter_isUsed = 0u;
	exiFrag->PaymentDetailsRes_isUsed = 0u;
	exiFrag->PaymentDetailsReq_isUsed = 0u;
	exiFrag->MgmtData_isUsed = 0u;
	exiFrag->Value_isUsed = 0u;
	exiFrag->EVSENotification_isUsed = 0u;
	exiFrag->EVSENotification_isUsed = 0u;
	exiFrag->EVSEMaximumPowerLimit_isUsed = 0u;
	exiFrag->EVTargetCurrent_isUsed = 0u;
	exiFrag->RemainingTimeToBulkSoC_isUsed = 0u;
	exiFrag->EVTargetCurrent_isUsed = 0u;
	exiFrag->SessionSetupReq_isUsed = 0u;
	exiFrag->EVSECurrentLimitAchieved_isUsed = 0u;
	exiFrag->ServiceDetailReq_isUsed = 0u;
	exiFrag->byteValue_isUsed = 0u;
	exiFrag->EVMaximumPowerLimit_isUsed = 0u;
	exiFrag->PowerSwitchClosed_isUsed = 0u;
	exiFrag->Manifest_isUsed = 0u;
	exiFrag->P_isUsed = 0u;
	exiFrag->SAScheduleList_isUsed = 0u;
	exiFrag->Q_isUsed = 0u;
	exiFrag->X509SubjectName_isUsed = 0u;
	exiFrag->G_isUsed = 0u;
	exiFrag->SessionID_isUsed = 0u;
	exiFrag->J_isUsed = 0u;
	exiFrag->CertificateInstallationRes_isUsed = 0u;
	exiFrag->CertificateInstallationReq_isUsed = 0u;
	exiFrag->SalesTariff_isUsed = 0u;
	exiFrag->Header_isUsed = 0u;
	exiFrag->EVSEMinimumCurrentLimit_isUsed = 0u;
	exiFrag->X509CRL_isUsed = 0u;
	exiFrag->EVMaximumCurrentLimit_isUsed = 0u;
	exiFrag->Y_isUsed = 0u;
	exiFrag->DigestValue_isUsed = 0u;
	exiFrag->DC_EVChargeParameter_isUsed = 0u;
	exiFrag->ContractSignatureEncryptedPrivateKey_isUsed = 0u;
	exiFrag->ContractSignatureEncryptedPrivateKey_isUsed = 0u;
	exiFrag->DigestMethod_isUsed = 0u;
	exiFrag->SPKISexp_isUsed = 0u;
	exiFrag->ChargeService_isUsed = 0u;
	exiFrag->EVSEEnergyToBeDelivered_isUsed = 0u;
	exiFrag->SignatureProperties_isUsed = 0u;
	exiFrag->EVSEMaxCurrent_isUsed = 0u;
	exiFrag->EVMaximumPowerLimit_isUsed = 0u;
	exiFrag->EVSEStatus_isUsed = 0u;
	exiFrag->Service_isUsed = 0u;
	exiFrag->DHParams_isUsed = 0u;
	exiFrag->DHParams_isUsed = 0u;
	exiFrag->DHParams_isUsed = 0u;
	exiFrag->DHParams_isUsed = 0u;
	exiFrag->PGPKeyID_isUsed = 0u;
	exiFrag->DSAKeyValue_isUsed = 0u;
	exiFrag->EnergyTransferType_isUsed = 0u;
	exiFrag->WeldingDetectionRes_isUsed = 0u;
	exiFrag->FreeService_isUsed = 0u;
	exiFrag->SelectedServiceList_isUsed = 0u;
	exiFrag->WeldingDetectionReq_isUsed = 0u;
	exiFrag->EVTargetVoltage_isUsed = 0u;
	exiFrag->EVTargetVoltage_isUsed = 0u;
	exiFrag->CanonicalizationMethod_isUsed = 0u;
	exiFrag->X509Certificate_isUsed = 0u;
	exiFrag->CertificateUpdateRes_isUsed = 0u;
	exiFrag->CertificateUpdateReq_isUsed = 0u;
	exiFrag->EVSEMaxVoltage_isUsed = 0u;
	exiFrag->SignedInfo_isUsed = 0u;
	exiFrag->AC_EVSEChargeParameter_isUsed = 0u;
	exiFrag->EVEnergyCapacity_isUsed = 0u;
	exiFrag->ServiceID_isUsed = 0u;
	exiFrag->ServiceID_isUsed = 0u;
	exiFrag->EVSECurrentRegulationTolerance_isUsed = 0u;
	exiFrag->ServiceParameterList_isUsed = 0u;
	exiFrag->ListOfRootCertificateIDs_isUsed = 0u;
	exiFrag->ListOfRootCertificateIDs_isUsed = 0u;
	exiFrag->ProfileEntry_isUsed = 0u;
	exiFrag->EVSEMinimumVoltageLimit_isUsed = 0u;
	exiFrag->CurrentDemandRes_isUsed = 0u;
	exiFrag->EVRESSSOC_isUsed = 0u;
	exiFrag->MeterReading_isUsed = 0u;
	exiFrag->CurrentDemandReq_isUsed = 0u;
	exiFrag->physicalValue_isUsed = 0u;
	exiFrag->ChargingComplete_isUsed = 0u;
	exiFrag->TimeInterval_isUsed = 0u;
	exiFrag->AC_EVSEStatus_isUsed = 0u;
	exiFrag->AC_EVSEStatus_isUsed = 0u;
	exiFrag->EVMaximumVoltageLimit_isUsed = 0u;
	exiFrag->SignatureValue_isUsed = 0u;
	exiFrag->DateTimeNow_isUsed = 0u;
	exiFrag->DateTimeNow_isUsed = 0u;
	exiFrag->ServiceTag_isUsed = 0u;
	exiFrag->intValue_isUsed = 0u;
	exiFrag->SelectedPaymentOption_isUsed = 0u;
	exiFrag->ServiceName_isUsed = 0u;
	exiFrag->EVCabinConditioning_isUsed = 0u;
	exiFrag->EVSEID_isUsed = 0u;
	exiFrag->ServiceScope_isUsed = 0u;
	exiFrag->EVSEID_isUsed = 0u;
	exiFrag->MeterStatus_isUsed = 0u;
	exiFrag->EVRequestedEnergyTransferType_isUsed = 0u;
	exiFrag->ServiceCategory_isUsed = 0u;
	exiFrag->GenChallenge_isUsed = 0u;
	exiFrag->GenChallenge_isUsed = 0u;
	exiFrag->SalesTariffDescription_isUsed = 0u;
	exiFrag->NotificationMaxDelay_isUsed = 0u;
	exiFrag->NotificationMaxDelay_isUsed = 0u;
	exiFrag->boolValue_isUsed = 0u;
	exiFrag->EVSEStatusCode_isUsed = 0u;
	exiFrag->ServiceScope_isUsed = 0u;
	exiFrag->FaultMsg_isUsed = 0u;
	exiFrag->SAScheduleTupleID_isUsed = 0u;
	exiFrag->SAScheduleTupleID_isUsed = 0u;
	exiFrag->BulkChargingComplete_isUsed = 0u;
	exiFrag->KeyName_isUsed = 0u;
	exiFrag->ParameterSet_isUsed = 0u;
	exiFrag->SigMeterReading_isUsed = 0u;
	exiFrag->EVSEChargeParameter_isUsed = 0u;
	exiFrag->Body_isUsed = 0u;
	exiFrag->SASchedules_isUsed = 0u;
	exiFrag->ServiceCategory_isUsed = 0u;
	exiFrag->KeyInfo_isUsed = 0u;
	exiFrag->PMaxScheduleID_isUsed = 0u;
	exiFrag->RemainingTimeToFullSoC_isUsed = 0u;
	exiFrag->EVStatus_isUsed = 0u;
	exiFrag->SubCertificates_isUsed = 0u;
	exiFrag->PaymentOption_isUsed = 0u;
	exiFrag->X509SKI_isUsed = 0u;
	exiFrag->EVMaximumVoltageLimit_isUsed = 0u;
	exiFrag->ServiceList_isUsed = 0u;
	exiFrag->Cost_isUsed = 0u;
	exiFrag->AC_EVSEStatus_isUsed = 0u;
	exiFrag->AC_EVSEStatus_isUsed = 0u;
	exiFrag->SignatureMethod_isUsed = 0u;
	exiFrag->EVSEMinCurrent_isUsed = 0u;
	exiFrag->ConsumptionCost_isUsed = 0u;
	exiFrag->EVSEPeakCurrentRipple_isUsed = 0u;
	exiFrag->EVErrorCode_isUsed = 0u;
	exiFrag->EVChargeParameter_isUsed = 0u;
	exiFrag->start_isUsed = 0u;
	exiFrag->X509IssuerName_isUsed = 0u;
	exiFrag->Reference_isUsed = 0u;
	exiFrag->EVMinCurrent_isUsed = 0u;
	exiFrag->FullSOC_isUsed = 0u;
	exiFrag->amount_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->DC_EVSEStatus_isUsed = 0u;
	exiFrag->shortValue_isUsed = 0u;
	exiFrag->DC_EVSEChargeParameter_isUsed = 0u;
	exiFrag->Entry_isUsed = 0u;
	exiFrag->ServiceID_isUsed = 0u;
	exiFrag->ServiceID_isUsed = 0u;
	exiFrag->SalesTariffID_isUsed = 0u;
	exiFrag->MeterID_isUsed = 0u;
	exiFrag->EVSEMaximumCurrentLimit_isUsed = 0u;
	exiFrag->ChargeParameterDiscoveryReq_isUsed = 0u;
	exiFrag->amountMultiplier_isUsed = 0u;
	exiFrag->ChargeParameterDiscoveryRes_isUsed = 0u;
	exiFrag->Transform_isUsed = 0u;
	exiFrag->Object_isUsed = 0u;
	exiFrag->RCD_isUsed = 0u;
	exiFrag->Notification_isUsed = 0u;
	exiFrag->startValue_isUsed = 0u;
	exiFrag->Modulus_isUsed = 0u;
	exiFrag->EVSEMaxCurrent_isUsed = 0u;
}
#endif /* DEPLOY_DIN_CODEC_FRAGMENT */

void init_dinMeteringReceiptReqType(struct dinMeteringReceiptReqType* dinMeteringReceiptReqType) {
	// printf("[C] sizeof dinMeteringReceiptReqType = %ld\n", sizeof(struct dinMeteringReceiptReqType));
	// printf("[C] TMeter = %ld\n", dinMeteringReceiptReqType->MeterInfo.TMeter);
	// validated
	dinMeteringReceiptReqType->Id_isUsed = 0u;
	dinMeteringReceiptReqType->SAScheduleTupleID_isUsed = 0u;
}

void init_dinBodyType(struct dinBodyType* dinBodyType) {
	// printf("[C] sizeof dinBodyType = %ld\n", sizeof(struct dinBodyType));
	// printf("[C] session setup req is used = %d\n", dinBodyType->SessionSetupReq_isUsed);
	// validated

	dinBodyType->BodyElement_isUsed = 0u;
	dinBodyType->SessionSetupReq_isUsed = 0u;
	dinBodyType->SessionSetupRes_isUsed = 0u;
	dinBodyType->ServiceDiscoveryReq_isUsed = 0u;
	dinBodyType->ServiceDiscoveryRes_isUsed = 0u;
	dinBodyType->ServiceDetailReq_isUsed = 0u;
	dinBodyType->ServiceDetailRes_isUsed = 0u;
	dinBodyType->ServicePaymentSelectionReq_isUsed = 0u;
	dinBodyType->ServicePaymentSelectionRes_isUsed = 0u;
	dinBodyType->PaymentDetailsReq_isUsed = 0u;
	dinBodyType->PaymentDetailsRes_isUsed = 0u;
	dinBodyType->ContractAuthenticationReq_isUsed = 0u;
	dinBodyType->ContractAuthenticationRes_isUsed = 0u;
	dinBodyType->ChargeParameterDiscoveryReq_isUsed = 0u;
	dinBodyType->ChargeParameterDiscoveryRes_isUsed = 0u;
	dinBodyType->PowerDeliveryReq_isUsed = 0u;
	dinBodyType->PowerDeliveryRes_isUsed = 0u;
	dinBodyType->ChargingStatusReq_isUsed = 0u;
	dinBodyType->ChargingStatusRes_isUsed = 0u;
	dinBodyType->MeteringReceiptReq_isUsed = 0u;
	dinBodyType->MeteringReceiptRes_isUsed = 0u;
	dinBodyType->SessionStopReq_isUsed = 0u;
	dinBodyType->SessionStopRes_isUsed = 0u;
	dinBodyType->CertificateUpdateReq_isUsed = 0u;
	dinBodyType->CertificateUpdateRes_isUsed = 0u;
	dinBodyType->CertificateInstallationReq_isUsed = 0u;
	dinBodyType->CertificateInstallationRes_isUsed = 0u;
	dinBodyType->CableCheckReq_isUsed = 0u;
	dinBodyType->CableCheckRes_isUsed = 0u;
	dinBodyType->PreChargeReq_isUsed = 0u;
	dinBodyType->PreChargeRes_isUsed = 0u;
	dinBodyType->CurrentDemandReq_isUsed = 0u;
	dinBodyType->CurrentDemandRes_isUsed = 0u;
	dinBodyType->WeldingDetectionReq_isUsed = 0u;
	dinBodyType->WeldingDetectionRes_isUsed = 0u;
}

void init_dinSessionSetupReqType(struct dinSessionSetupReqType* dinSessionSetupReqType) {
	// printf("[C] dinSessionSetupReqType->EVCCID.bytesLen = %d\n", dinSessionSetupReqType->EVCCID.bytesLen);
	// printf("[C] dinSessionSetupReqType->EVCCID.bytes = ");

	// int i = 0;
	// for(; i < dinSessionSetupReqType->EVCCID.bytesLen; i++){
	// 	printf("0x%x\n", dinSessionSetupReqType->EVCCID.bytes[i]);
	// }

	// printf("\n");
	// validated !

	(void)dinSessionSetupReqType; /* avoid unused warning */
}

void init_dinPowerDeliveryResType(struct dinPowerDeliveryResType* dinPowerDeliveryResType) {
	// printf("[C] sizeof dinPowerDeliveryResType = %ld\n", sizeof(struct dinPowerDeliveryResType));
	// printf("[C] pointer = %p\n", dinPowerDeliveryResType);

	// printf("[C] ResponseCode = %d\n", dinPowerDeliveryResType->ResponseCode);
	// printf("[C] AC_EVSEStatus_isUsed = %d\n", dinPowerDeliveryResType->AC_EVSEStatus_isUsed);
	// printf("[C] DC_EVSEStatus_isUsed = %d\n", dinPowerDeliveryResType->DC_EVSEStatus_isUsed);
	// printf("[C] EVSEStatus_isUsed = %d\n", dinPowerDeliveryResType->EVSEStatus_isUsed);
	// printf("[C] AC_EVSEStatus.EVSENotification = %d\n", dinPowerDeliveryResType->AC_EVSEStatus.EVSENotification);
	// printf("[C] AC_EVSEStatus.NotificationMaxDelay = %d\n", dinPowerDeliveryResType->AC_EVSEStatus.NotificationMaxDelay);
	// printf("[C] AC_EVSEStatus.PowerSwitchClosed = %d\n", dinPowerDeliveryResType->AC_EVSEStatus.PowerSwitchClosed);
	// printf("[C] AC_EVSEStatus.RCD = %d\n", dinPowerDeliveryResType->AC_EVSEStatus.RCD);
	// validated	
	dinPowerDeliveryResType->EVSEStatus_isUsed = 0u;
	dinPowerDeliveryResType->AC_EVSEStatus_isUsed = 0u;
	dinPowerDeliveryResType->DC_EVSEStatus_isUsed = 0u;
}

void init_dinServiceDetailResType(struct dinServiceDetailResType* dinServiceDetailResType) {
	// printf("[C] pointer = %p\n", dinServiceDetailResType);
	// printf("[C] sizeof dinPowerDeliveryResType = %ld\n", sizeof(struct dinServiceDetailResType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(dinServiceDetailResType->);
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] offsetof(dinParameterType, Name) = %ld\n", offsetof(struct dinParameterType, Name));
	// printf("[C] offsetof(dinParameterType, ValueType) = %ld\n", offsetof(struct dinParameterType, ValueType));
	// printf("[C] offsetof(dinParameterType, boolValue) = %ld\n", offsetof(struct dinParameterType, boolValue));
	// printf("[C] offsetof(dinParameterType, shortValue) = %ld\n", offsetof(struct dinParameterType, shortValue));
	// printf("[C] offsetof(dinParameterType, intValue) = %ld\n", offsetof(struct dinParameterType, intValue));
	// printf("[C] offsetof(dinParameterType, physicalValue) = %ld\n", offsetof(struct dinParameterType, physicalValue));
	// printf("[C] offsetof(dinParameterType, stringValue) = %ld\n", offsetof(struct dinParameterType, stringValue));
	// printf("[C] sizeof dinPhysicalValueType = %ld\n", sizeof(struct dinPhysicalValueType));
	// printf("[C] sizeof dinParameterSetType = %ld\n", sizeof(struct dinParameterSetType));
	// printf("[C] sizeof dinServiceParameterListType = %ld\n", sizeof(struct dinServiceParameterListType));
	// printf("[C] dinServiceDetailResType->ResponseCode = %d\n", dinServiceDetailResType->ResponseCode);
	// printf("[C] dinServiceDetailResType->ServiceID = %d\n", dinServiceDetailResType->ServiceID);
	// printf("[C] dinServiceDetailResType->ServiceParameterList_isUsed = %d\n", dinServiceDetailResType->ServiceParameterList_isUsed);
	// validated

	dinServiceDetailResType->ServiceParameterList_isUsed = 0u;
}

void init_dinWeldingDetectionResType(struct dinWeldingDetectionResType* dinWeldingDetectionResType) {
	// printf("[C] sizeof dinWeldingDetectionResType = %ld\n", sizeof(struct dinWeldingDetectionResType));
	
	// printf("[C] dinWeldingDetectionResType->ResponseCode = %d\n", dinWeldingDetectionResType->ResponseCode);
	// printf("[C] dinWeldingDetectionResType->DC_EVSEStatus.EVSEIsolationStatus = %d\n", dinWeldingDetectionResType->DC_EVSEStatus.EVSEIsolationStatus);
	// printf("[C] dinWeldingDetectionResType->EVSEPresentVoltage.Value = %d\n", dinWeldingDetectionResType->EVSEPresentVoltage.Value);
	// validated
	(void)dinWeldingDetectionResType; /* avoid unused warning */
}

void init_dinContractAuthenticationResType(struct dinContractAuthenticationResType* dinContractAuthenticationResType) {
	// printf("[C] sizeof dinContractAuthenticationResType = %ld\n", sizeof(struct dinContractAuthenticationResType));
	// printf("[C] dinContractAuthenticationResType->ResponseCode = %d\n", dinContractAuthenticationResType->ResponseCode );
	// printf("[C] dinContractAuthenticationResType->EVSEProcessing = %d\n", dinContractAuthenticationResType->EVSEProcessing );
	// validated

	(void)dinContractAuthenticationResType; /* avoid unused warning */
}

void init_dinCanonicalizationMethodType(struct dinCanonicalizationMethodType* dinCanonicalizationMethodType) {
	// printf("[C] sizeof dinCanonicalizationMethodType = %ld\n", sizeof(struct dinCanonicalizationMethodType));
	// printf("[C] dinCanonicalizationMethodType->Algorithm.characters = %ls\n", dinCanonicalizationMethodType->Algorithm.characters );
	// printf("[C] dinCanonicalizationMethodType->Algorithm.charactersLen = %d\n", dinCanonicalizationMethodType->Algorithm.charactersLen );

	// printf("[C] dinCanonicalizationMethodType->ANY.characters = %ls\n", dinCanonicalizationMethodType->ANY.characters );
	// printf("[C] dinCanonicalizationMethodType->ANY.charactersLen = %d\n", dinCanonicalizationMethodType->ANY.charactersLen );
	// validated
	
	dinCanonicalizationMethodType->ANY_isUsed = 0u;
}

void init_dinSPKIDataType(struct dinSPKIDataType* dinSPKIDataType) {
	// printf("[C] sizeof dinSPKIDataType = %ld\n", sizeof(struct dinSPKIDataType));
	// printf("[C] dinSPKIDataType->SPKISexp.array[0].bytes = ");
	// int i = 0;
	// for(; i < dinSPKIDataType->SPKISexp.array[0].bytesLen; i++){
	// 	printf("%x ", dinSPKIDataType->SPKISexp.array[0].bytes[i]);
	// }
	// printf("\n");
	// printf("[C] dinSPKIDataType->SPKISexp.array[0].bytesLen = %d\n", dinSPKIDataType->SPKISexp.array[0].bytesLen);
	// printf("[C] dinSPKIDataType->ANY.characters = %ls\n", dinSPKIDataType->ANY.characters);
	// printf("[C] dinSPKIDataType->ANY.charactersLen = %d\n", dinSPKIDataType->ANY.charactersLen);
	// printf("[C] dinSPKIDataType->ANY_isUsed = %d\n", dinSPKIDataType->ANY_isUsed);
	// validated
	dinSPKIDataType->SPKISexp.arrayLen = 0u;
	dinSPKIDataType->ANY_isUsed = 0u;
}

void init_dinListOfRootCertificateIDsType(struct dinListOfRootCertificateIDsType* dinListOfRootCertificateIDsType) {
	// printf("[C] sizeof dinListOfRootCertificateIDsType = %ld\n", sizeof(struct dinListOfRootCertificateIDsType));
	// printf("[C] dinListOfRootCertificateIDsType->RootCertificateID.arrayLen = %d\n", dinListOfRootCertificateIDsType->RootCertificateID.arrayLen);

	// int i = 0;
	// for(; i < dinListOfRootCertificateIDsType->RootCertificateID.arrayLen; i++){
	// 	printf("[C] dinListOfRootCertificateIDsType->RootCertificateID.array[%d].characters = %ls\n", i, dinListOfRootCertificateIDsType->RootCertificateID.array[i].characters);
	// 	printf("[C] dinListOfRootCertificateIDsType->RootCertificateID.array[%d].charactersLen = %d\n", i, dinListOfRootCertificateIDsType->RootCertificateID.array[i].charactersLen);

	// }
	// validated
	dinListOfRootCertificateIDsType->RootCertificateID.arrayLen = 0u;
}

void init_dinSelectedServiceListType(struct dinSelectedServiceListType* dinSelectedServiceListType) {
	// int i = 0;
	// for(; i < dinSelectedServiceListType->SelectedService.arrayLen; i++){
	// 	printf("[C] dinSelectedServiceListType->SelectedService.array[%d].ServiceID = %d\n", i, dinSelectedServiceListType->SelectedService.array[i].ServiceID );
	// 	printf("[C] dinSelectedServiceListType->SelectedService.array[%d].ParameterSetID = %d\n", i, dinSelectedServiceListType->SelectedService.array[i].ParameterSetID );
	// 	printf("[C] dinSelectedServiceListType->SelectedService.array[%d].ParameterSetID_isUsed = %d\n", i, dinSelectedServiceListType->SelectedService.array[i].ParameterSetID_isUsed );
	// }
	// validated

	dinSelectedServiceListType->SelectedService.arrayLen = 0u;
}

void init_dinCurrentDemandResType(struct dinCurrentDemandResType* dinCurrentDemandResType) {
	// printf("[C] sizeof dinCurrentDemandResType = %ld\n", sizeof(struct dinCurrentDemandResType));
	// printf("[C] dinCurrentDemandResType->ResponseCode = %d\n", dinCurrentDemandResType->ResponseCode);
	// printf("[C] dinCurrentDemandResType->EVSEMaximumVoltageLimit_isUsed = %d\n", dinCurrentDemandResType->EVSEMaximumVoltageLimit_isUsed);
	// printf("[C] dinCurrentDemandResType->EVSEMaximumCurrentLimit_isUsed = %d\n", dinCurrentDemandResType->EVSEMaximumCurrentLimit_isUsed);
	// printf("[C] dinCurrentDemandResType->EVSEMaximumPowerLimit_isUsed = %d\n", dinCurrentDemandResType->EVSEMaximumPowerLimit_isUsed);
	// validated

	dinCurrentDemandResType->EVSEMaximumVoltageLimit_isUsed = 0u;
	dinCurrentDemandResType->EVSEMaximumCurrentLimit_isUsed = 0u;
	dinCurrentDemandResType->EVSEMaximumPowerLimit_isUsed = 0u;
}

void init_dinTransformType(struct dinTransformType* dinTransformType) {
	// printf("[C] sizeof dinTransformType = %ld\n", sizeof(struct dinTransformType));
	// printf("[C] dinTransformType->Algorithm.characters = %ls\n", dinTransformType->Algorithm.characters);
	// printf("[C] dinTransformType->Algorithm.charactersLen = %d\n", dinTransformType->Algorithm.charactersLen);
	// printf("[C] dinTransformType->ANY.characters = %ls\n", dinTransformType->ANY.characters);
	// printf("[C] dinTransformType->ANY.charactersLen = %d\n", dinTransformType->ANY.charactersLen);
	// printf("[C] dinTransformType->ANY_isUsed = %d\n", dinTransformType->ANY_isUsed);
	// printf("[C] dinTransformType->XPath.array[0].characters = %ls\n", dinTransformType->XPath.array[0].characters);
	// printf("[C] dinTransformType->XPath.array[0].charactersLen = %d\n", dinTransformType->XPath.array[0].charactersLen);
	// validated

	dinTransformType->ANY_isUsed = 0u;
	dinTransformType->XPath.arrayLen = 0u;
}

void init_dinAC_EVChargeParameterType(struct dinAC_EVChargeParameterType* dinAC_EVChargeParameterType) {
	// printf("[C] dinAC_EVChargeParameterType->DepartureTime = %d\n", dinAC_EVChargeParameterType->DepartureTime);
	// printf("[C] dinAC_EVChargeParameterType->EVMaxVoltage.Value = %d\n", dinAC_EVChargeParameterType->EVMaxVoltage.Value);
	// printf("[C] dinAC_EVChargeParameterType->EVMaxCurrent.Value = %d\n", dinAC_EVChargeParameterType->EVMaxCurrent.Value);
	// printf("[C] dinAC_EVChargeParameterType->EVMinCurrent.Value = %d\n", dinAC_EVChargeParameterType->EVMinCurrent.Value);
	// validated

	(void)dinAC_EVChargeParameterType; /* avoid unused warning */
}

void init_dinX509DataType(struct dinX509DataType* dinX509DataType) {
	// printf("[C] dinX509DataType->X509IssuerSerial.arrayLen = %d\n", dinX509DataType->X509IssuerSerial.arrayLen);
	// printf("[C] dinX509DataType->X509SKI.arrayLen = %d\n", dinX509DataType->X509SKI.arrayLen);
	// printf("[C] dinX509DataType->X509SubjectName.arrayLen = %d\n", dinX509DataType->X509SubjectName.arrayLen);
	// printf("[C] dinX509DataType->X509Certificate.arrayLen = %d\n", dinX509DataType->X509Certificate.arrayLen);
	// printf("[C] dinX509DataType->X509CRL.arrayLen = %d\n", dinX509DataType->X509CRL.arrayLen);
	// printf("[C] dinX509DataType->ANY_isUsed = %d\n", dinX509DataType->ANY_isUsed);
	// printf("[C] dinX509DataType->X509IssuerSerial.array[0].X509IssuerName.characters = %ls\n", dinX509DataType->X509IssuerSerial.array[0].X509IssuerName.characters);
	// printf("[C] dinX509DataType->X509SKI.arrayLen = %d\n", dinX509DataType->X509SKI.arrayLen);
	// printf("[C] dinX509DataType->X509SubjectName.arrayLen = %d\n", dinX509DataType->X509SubjectName.arrayLen);
	// printf("[C] dinX509DataType->X509Certificate.arrayLen = %d\n", dinX509DataType->X509Certificate.arrayLen);
	// printf("[C] dinX509DataType->X509CRL.arrayLen = %d\n", dinX509DataType->X509CRL.arrayLen);
	// printf("[C] dinX509DataType->ANY_isUsed = %d\n", dinX509DataType->ANY_isUsed);
	// validated
	
	dinX509DataType->X509IssuerSerial.arrayLen = 0u;
	dinX509DataType->X509SKI.arrayLen = 0u;
	dinX509DataType->X509SubjectName.arrayLen = 0u;
	dinX509DataType->X509Certificate.arrayLen = 0u;
	dinX509DataType->X509CRL.arrayLen = 0u;
	dinX509DataType->ANY_isUsed = 0u;
}

void init_dinChargingStatusResType(struct dinChargingStatusResType* dinChargingStatusResType) {
	// printf("[C] sizeof dinChargingStatusResType = %ld\n", sizeof(struct dinChargingStatusResType));
	// printf("[C] dinChargingStatusResType->AC_EVSEStatus.EVSENotification = %d\n", dinChargingStatusResType->AC_EVSEStatus.EVSENotification);
	// printf("[C] dinChargingStatusResType->AC_EVSEStatus.NotificationMaxDelay = %d\n", dinChargingStatusResType->AC_EVSEStatus.NotificationMaxDelay);
	// printf("[C] dinChargingStatusResType->AC_EVSEStatus.PowerSwitchClosed = %d\n", dinChargingStatusResType->AC_EVSEStatus.PowerSwitchClosed);
	// printf("[C] dinChargingStatusResType->AC_EVSEStatus.RCD = %d\n", dinChargingStatusResType->AC_EVSEStatus.RCD);
	// printf("[C] dinChargingStatusResType->EVSEID.bytesLen = %d\n", dinChargingStatusResType->EVSEID.bytesLen);
	// printf("[C] dinChargingStatusResType->EVSEMaxCurrent.Multiplier = %d\n", dinChargingStatusResType->EVSEMaxCurrent.Multiplier);
	// printf("[C] dinChargingStatusResType->EVSEMaxCurrent.Unit = %d\n", dinChargingStatusResType->EVSEMaxCurrent.Unit);
	// printf("[C] dinChargingStatusResType->EVSEMaxCurrent.Unit_isUsed = %d\n", dinChargingStatusResType->EVSEMaxCurrent.Unit_isUsed);
	// printf("[C] dinChargingStatusResType->EVSEMaxCurrent.Value = %d\n", dinChargingStatusResType->EVSEMaxCurrent.Value);
	// printf("[C] dinChargingStatusResType->EVSEMaxCurrent_isUsed = %d\n", dinChargingStatusResType->EVSEMaxCurrent_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterID.characters = %ls\n", dinChargingStatusResType->MeterInfo.MeterID.characters);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterID.charactersLen = %d\n", dinChargingStatusResType->MeterInfo.MeterID.charactersLen);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterReading.Multiplier = %d\n", dinChargingStatusResType->MeterInfo.MeterReading.Multiplier);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterReading.Unit = %d\n", dinChargingStatusResType->MeterInfo.MeterReading.Unit);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterReading.Unit_isUsed = %d\n", dinChargingStatusResType->MeterInfo.MeterReading.Unit_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterReading.Value = %d\n", dinChargingStatusResType->MeterInfo.MeterReading.Value);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterReading_isUsed = %d\n", dinChargingStatusResType->MeterInfo.MeterReading_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterStatus = %d\n", dinChargingStatusResType->MeterInfo.MeterStatus);
	// printf("[C] dinChargingStatusResType->MeterInfo.MeterStatus_isUsed = %d\n", dinChargingStatusResType->MeterInfo.MeterStatus_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo.SigMeterReading.bytesLen = %d\n", dinChargingStatusResType->MeterInfo.SigMeterReading.bytesLen);
	// printf("[C] dinChargingStatusResType->MeterInfo.SigMeterReading_isUsed = %d\n", dinChargingStatusResType->MeterInfo.SigMeterReading_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo.TMeter = %ld\n", dinChargingStatusResType->MeterInfo.TMeter);
	// printf("[C] dinChargingStatusResType->MeterInfo.TMeter_isUsed = %d\n", dinChargingStatusResType->MeterInfo.TMeter_isUsed);
	// printf("[C] dinChargingStatusResType->MeterInfo_isUsed = %d\n", dinChargingStatusResType->MeterInfo_isUsed);
	// printf("[C] dinChargingStatusResType->ReceiptRequired = %d\n", dinChargingStatusResType->ReceiptRequired);
	// printf("[C] dinChargingStatusResType->ResponseCode = %d\n", dinChargingStatusResType->ResponseCode);
	// printf("[C] dinChargingStatusResType->SAScheduleTupleID = %d\n", dinChargingStatusResType->SAScheduleTupleID);
	// validated
	dinChargingStatusResType->EVSEMaxCurrent_isUsed = 0u;
	dinChargingStatusResType->MeterInfo_isUsed = 0u;

	
}

void init_dinWeldingDetectionReqType(struct dinWeldingDetectionReqType* dinWeldingDetectionReqType) {
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVCabinConditioning = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVCabinConditioning);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVCabinConditioning_isUsed = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVCabinConditioning_isUsed);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVErrorCode = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVErrorCode);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVReady = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVReady);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVRESSConditioning = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVRESSConditioning);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVRESSConditioning_isUsed = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVRESSConditioning_isUsed);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVErrorCode = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVErrorCode);
	// printf("[C] dinWeldingDetectionReqType->DC_EVStatusType.EVRESSSOC = %d\n", dinWeldingDetectionReqType->DC_EVStatus.EVRESSSOC);
	// validated
	(void)dinWeldingDetectionReqType; /* avoid unused warning */
}

void init_dinSignaturePropertiesType(struct dinSignaturePropertiesType* dinSignaturePropertiesType) {
	// printf("[C] dinSignaturePropertiesType->Id.characters = %ls\n", dinSignaturePropertiesType->Id.characters);
	// printf("[C] dinSignaturePropertiesType->SignatureProperty.array[0].ANY = %ls\n", dinSignaturePropertiesType->SignatureProperty.array[0].ANY.characters);
	// printf("[C] dinSignaturePropertiesType->SignatureProperty.array[0].ANY_isUsed = %d\n", dinSignaturePropertiesType->SignatureProperty.array[0].ANY_isUsed );
	// printf("[C] dinSignaturePropertiesType->SignatureProperty.array[0].Id = %ls\n", dinSignaturePropertiesType->SignatureProperty.array[0].Id.characters);
	// printf("[C] dinSignaturePropertiesType->SignatureProperty.array[0].Id_isUsed = %d\n", dinSignaturePropertiesType->SignatureProperty.array[0].Id_isUsed );
	// printf("[C] dinSignaturePropertiesType->SignatureProperty.array[0].Target = %ls\n", dinSignaturePropertiesType->SignatureProperty.array[0].Target.characters);
	// validated
	dinSignaturePropertiesType->Id_isUsed = 0u;
	dinSignaturePropertiesType->SignatureProperty.arrayLen = 0u;
}

void init_dinContractAuthenticationReqType(struct dinContractAuthenticationReqType* dinContractAuthenticationReqType) {
	// printf("[C] dinContractAuthenticationReqType->GenChallenge.characters = %ls\n", dinContractAuthenticationReqType->GenChallenge.characters);
	// printf("[C] dinContractAuthenticationReqType->GenChallenge.charactersLen = %d\n", dinContractAuthenticationReqType->GenChallenge.charactersLen);
	// printf("[C] dinContractAuthenticationReqType->GenChallenge_isUsed = %d\n", dinContractAuthenticationReqType->GenChallenge_isUsed);
	// printf("[C] dinContractAuthenticationReqType->Id.characters = %ls\n", dinContractAuthenticationReqType->Id.characters);
	// printf("[C] dinContractAuthenticationReqType->Id.charactersLen = %d\n", dinContractAuthenticationReqType->Id.charactersLen);
	// printf("[C] dinContractAuthenticationReqType->Id_isUsed = %d\n", dinContractAuthenticationReqType->Id_isUsed);
	// validated
	dinContractAuthenticationReqType->Id_isUsed = 0u;
	dinContractAuthenticationReqType->GenChallenge_isUsed = 0u;
}

void init_dinDC_EVPowerDeliveryParameterType(struct dinDC_EVPowerDeliveryParameterType* dinDC_EVPowerDeliveryParameterType) {
	// printf("[C] sizeof dinDC_EVPowerDeliveryParameterType = %ld\n", sizeof(struct dinDC_EVPowerDeliveryParameterType));
	// printf("[C] sizeof dinDC_EVStatusType = %ld\n", sizeof(struct dinDC_EVStatusType));
	// printf("[c] offset dinDC_EVPowerDeliveryParameterType->BulkChargingComplete = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, BulkChargingComplete));
	// printf("[c] offset dinDC_EVPowerDeliveryParameterType->ChargingComplete = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, ChargingComplete));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVCabinConditioning = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVCabinConditioning));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVErrorCode));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVReady = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVReady));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSConditioning = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVRESSConditioning));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVErrorCode));
	// printf("[C] offset dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSSOC = %ld\n", offsetof(struct dinDC_EVPowerDeliveryParameterType, DC_EVStatus.EVRESSSOC));
	// printf("[c] dinDC_EVPowerDeliveryParameterType->BulkChargingComplete = %d\n", dinDC_EVPowerDeliveryParameterType->BulkChargingComplete);
	// printf("[c] dinDC_EVPowerDeliveryParameterType->BulkChargingComplete_isUsed = %d\n", dinDC_EVPowerDeliveryParameterType->BulkChargingComplete_isUsed);
	// printf("[c] dinDC_EVPowerDeliveryParameterType->ChargingComplete = %d\n", dinDC_EVPowerDeliveryParameterType->ChargingComplete);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVCabinConditioning = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVCabinConditioning);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVCabinConditioning_isUsed = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVCabinConditioning_isUsed);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVReady = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVReady);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSConditioning = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSConditioning);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSConditioning_isUsed = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSConditioning_isUsed);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVErrorCode);
	// printf("[C] dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSSOC = %d\n", dinDC_EVPowerDeliveryParameterType->DC_EVStatus.EVRESSSOC);
	// validated
	dinDC_EVPowerDeliveryParameterType->BulkChargingComplete_isUsed = 0u;
}

void init_dinEVSEChargeParameterType(struct dinEVSEChargeParameterType* dinEVSEChargeParameterType) {
	// validated
	(void)dinEVSEChargeParameterType; /* avoid unused warning */
}

void init_dinCableCheckReqType(struct dinCableCheckReqType* dinCableCheckReqType) {
	// printf("[C] dinCableCheckReqType->DC_EVStatus.EVRESSSOC = %d\n", dinCableCheckReqType->DC_EVStatus.EVRESSSOC);
	// validated
	(void)dinCableCheckReqType; /* avoid unused warning */
}

void init_dinDC_EVChargeParameterType(struct dinDC_EVChargeParameterType* dinDC_EVChargeParameterType) {
	// printf("[C] sizeof dinDC_EVChargeParameterType = %ld\n", sizeof(struct dinDC_EVChargeParameterType));
	// printf("[C] dinDC_EVChargeParameterType->EVMaximumPowerLimit_isUsed = %d\n", dinDC_EVChargeParameterType->EVMaximumPowerLimit_isUsed);
	// printf("[C] dinDC_EVChargeParameterType->EVEnergyCapacity_isUsed = %d\n", dinDC_EVChargeParameterType->EVEnergyCapacity_isUsed);
	// printf("[C] dinDC_EVChargeParameterType->EVEnergyRequest_isUsed = %d\n", dinDC_EVChargeParameterType->EVEnergyRequest_isUsed);
	// printf("[C] dinDC_EVChargeParameterType->FullSOC_isUsed = %d\n", dinDC_EVChargeParameterType->FullSOC_isUsed);
	// printf("[C] dinDC_EVChargeParameterType->BulkSOC_isUsed = %d\n", dinDC_EVChargeParameterType->BulkSOC_isUsed);
	// validated
	dinDC_EVChargeParameterType->EVMaximumPowerLimit_isUsed = 0u;
	dinDC_EVChargeParameterType->EVEnergyCapacity_isUsed = 0u;
	dinDC_EVChargeParameterType->EVEnergyRequest_isUsed = 0u;
	dinDC_EVChargeParameterType->FullSOC_isUsed = 0u;
	dinDC_EVChargeParameterType->BulkSOC_isUsed = 0u;
}

void init_dinSAScheduleListType(struct dinSAScheduleListType* dinSAScheduleListType) {
	// validated
	dinSAScheduleListType->SAScheduleTuple.arrayLen = 0u;
}

void init_dinPMaxScheduleType(struct dinPMaxScheduleType* dinPMaxScheduleType) {
	// printf("[C] dinPMaxScheduleType->PMaxScheduleEntry.array[1].PMax = %d\n", dinPMaxScheduleType->PMaxScheduleEntry.array[1].PMax);
	// validated
	dinPMaxScheduleType->PMaxScheduleEntry.arrayLen = 0u;
}

void init_dinServicePaymentSelectionReqType(struct dinServicePaymentSelectionReqType* dinServicePaymentSelectionReqType) {
	// printf("[C] parameter_set_id = %d\n", dinServicePaymentSelectionReqType->SelectedServiceList.SelectedService.array[1].ParameterSetID);
	// validated
	(void)dinServicePaymentSelectionReqType; /* avoid unused warning */
}

void init_dinRelativeTimeIntervalType(struct dinRelativeTimeIntervalType* dinRelativeTimeIntervalType) {
	// printf("[C] dinRelativeTimeIntervalType->start = %d\n", dinRelativeTimeIntervalType->start);
	// printf("[C] dinRelativeTimeIntervalType->duration = %d\n", dinRelativeTimeIntervalType->duration);
	// printf("[C] dinRelativeTimeIntervalType->duration_isUsed = %d\n", dinRelativeTimeIntervalType->duration_isUsed);
	// validated
	dinRelativeTimeIntervalType->duration_isUsed = 0u;
}

void init_dinEVStatusType(struct dinEVStatusType* dinEVStatusType) {
	// printf("[C] dinEVStatusType->noContent = %d\n", dinEVStatusType->noContent);
	// validated
	(void)dinEVStatusType; /* avoid unused warning */
}

void init_dinPreChargeResType(struct dinPreChargeResType* dinPreChargeResType) {
	// printf("[C] voltage = %d\n", dinPreChargeResType->EVSEPresentVoltage.Value);
	// validated
	(void)dinPreChargeResType; /* avoid unused warning */
}

void init_dinDC_EVSEChargeParameterType(struct dinDC_EVSEChargeParameterType* dinDC_EVSEChargeParameterType) {
	// printf("[C] energytobedelivered = %d\n", dinDC_EVSEChargeParameterType->EVSEEnergyToBeDelivered.Value);
	// validated
	dinDC_EVSEChargeParameterType->EVSEMaximumPowerLimit_isUsed = 0u;
	dinDC_EVSEChargeParameterType->EVSECurrentRegulationTolerance_isUsed = 0u;
	dinDC_EVSEChargeParameterType->EVSEEnergyToBeDelivered_isUsed = 0u;
}

void init_dinPaymentDetailsResType(struct dinPaymentDetailsResType* dinPaymentDetailsResType) {
	// printf("[C] datetime now = %ld\n", dinPaymentDetailsResType->DateTimeNow);
	// validated
	(void)dinPaymentDetailsResType; /* avoid unused warning */
}

void init_dinDSAKeyValueType(struct dinDSAKeyValueType* dinDSAKeyValueType) {
	// printf("[C] sizeof dinDSAKeyValueType = %ld\n", sizeof(struct dinDSAKeyValueType));
	// printf("[C] pgencounter = %d\n", dinDSAKeyValueType->PgenCounter.bytes[349]);
	// validated
	dinDSAKeyValueType->P_isUsed = 0u;
	dinDSAKeyValueType->Q_isUsed = 0u;
	dinDSAKeyValueType->G_isUsed = 0u;
	dinDSAKeyValueType->J_isUsed = 0u;
	dinDSAKeyValueType->Seed_isUsed = 0u;
	dinDSAKeyValueType->PgenCounter_isUsed = 0u;
}

void init_dinSASchedulesType(struct dinSASchedulesType* dinSASchedulesType) {
	// validated
	(void)dinSASchedulesType; /* avoid unused warning */
}

void init_dinCertificateUpdateResType(struct dinCertificateUpdateResType* dinCertificateUpdateResType) {
	// printf("[C] dinCertificateUpdateResType->RetryCounter = %d\n", dinCertificateUpdateResType->RetryCounter);
	// validated
	(void)dinCertificateUpdateResType; /* avoid unused warning */
}

void init_dinEVChargeParameterType(struct dinEVChargeParameterType* dinEVChargeParameterType) {
	// validated
	(void)dinEVChargeParameterType; /* avoid unused warning */
}

void init_dinMessageHeaderType(struct dinMessageHeaderType* dinMessageHeaderType) {
	// printf("[C] sizeof dinMessageHeaderType = %ld\n", sizeof(struct dinMessageHeaderType));
	// validated
	dinMessageHeaderType->Notification_isUsed = 0u;
	dinMessageHeaderType->Signature_isUsed = 0u;
}

void init_dinBodyBaseType(struct dinBodyBaseType* dinBodyBaseType) {
	// validated
	(void)dinBodyBaseType; /* avoid unused warning */
}

void init_dinKeyValueType(struct dinKeyValueType* dinKeyValueType) {
	// printf("[C] sizeof dinKeyValueType = %ld\n", sizeof(struct dinKeyValueType) );
	// printf("[C] any = %ls\n", dinKeyValueType->ANY.characters);
	// validated
	dinKeyValueType->DSAKeyValue_isUsed = 0u;
	dinKeyValueType->RSAKeyValue_isUsed = 0u;
	dinKeyValueType->ANY_isUsed = 0u;
}

void init_dinIntervalType(struct dinIntervalType* dinIntervalType) {
	// printf("[C] dinIntervalType->noContent = %d\n", dinIntervalType->noContent);
	// validated
	(void)dinIntervalType; /* avoid unused warning */
}

void init_dinChargeParameterDiscoveryResType(struct dinChargeParameterDiscoveryResType* dinChargeParameterDiscoveryResType) {
	// printf("[C] sizeof dinChargeParameterDiscoveryResType = %ld\n", sizeof(struct dinChargeParameterDiscoveryResType) );
	// printf("[C] energy to be delivered: %d\n", dinChargeParameterDiscoveryResType->DC_EVSEChargeParameter.EVSEEnergyToBeDelivered.Value);
	// validated
	dinChargeParameterDiscoveryResType->SASchedules_isUsed = 0u;
	dinChargeParameterDiscoveryResType->SAScheduleList_isUsed = 0u;
	dinChargeParameterDiscoveryResType->EVSEChargeParameter_isUsed = 0u;
	dinChargeParameterDiscoveryResType->AC_EVSEChargeParameter_isUsed = 0u;
	dinChargeParameterDiscoveryResType->DC_EVSEChargeParameter_isUsed = 0u;
}

void init_dinPowerDeliveryReqType(struct dinPowerDeliveryReqType* dinPowerDeliveryReqType) {
	// printf("[C] sizeof dinPowerDeliveryReqType = %ld\n", sizeof(struct dinPowerDeliveryReqType) );
	// printf("[C] resssoc = %d\n", dinPowerDeliveryReqType->DC_EVPowerDeliveryParameter.DC_EVStatus.EVRESSSOC);
	// validated
	dinPowerDeliveryReqType->ChargingProfile_isUsed = 0u;
	dinPowerDeliveryReqType->EVPowerDeliveryParameter_isUsed = 0u;
	dinPowerDeliveryReqType->DC_EVPowerDeliveryParameter_isUsed = 0u;
}

void init_dinCertificateChainType(struct dinCertificateChainType* dinCertificateChainType) {
	// printf("[C] dinCertificateChainType->SubCertificates.Certificate.array[1].bytesLen = %d\n", dinCertificateChainType->SubCertificates.Certificate.array[1].bytesLen);
	// validated
	dinCertificateChainType->SubCertificates_isUsed = 0u;
}

void init_dinTransformsType(struct dinTransformsType* dinTransformsType) {
	// printf("[C] sizeof  dinTransformsType = %ld\n", sizeof(struct dinTransformsType));
	// printf("%ls\n", dinTransformsType->Transform.array[0].Algorithm.characters);
	// validated
	dinTransformsType->Transform.arrayLen = 0u;
}

void init_dinEntryType(struct dinEntryType* dinEntryType) {
	// printf("[C] sizeof  dinEntryType = %ld\n", sizeof(struct dinEntryType));
	// printf("[C] duration = %d\n", dinEntryType->RelativeTimeInterval.duration);
	// validated
	dinEntryType->TimeInterval_isUsed = 0u;
	dinEntryType->RelativeTimeInterval_isUsed = 0u;
}

void init_dinSessionStopType(struct dinSessionStopType* dinSessionStopType) {
	// validated
	(void)dinSessionStopType; /* avoid unused warning */
}

void init_dinServiceDetailReqType(struct dinServiceDetailReqType* dinServiceDetailReqType) {
	// printf("[C] service_id = %d\n", dinServiceDetailReqType->ServiceID);
	// validated
	(void)dinServiceDetailReqType; /* avoid unused warning */
}

void init_dinDigestMethodType(struct dinDigestMethodType* dinDigestMethodType) {
	// printf("[C] sizeof dinDigestMethodType = %ld\n", sizeof(struct dinDigestMethodType));
	// printf("%ls\n", dinDigestMethodType->Algorithm.characters);
	// validated
	dinDigestMethodType->ANY_isUsed = 0u;
}

void init_dinParameterType(struct dinParameterType* dinParameterType) {
	// printf("[C] sizeof dinParameterType = %ld\n", sizeof(struct dinParameterType));
	// printf("[C] sizeof dinParameterType->Name = %ld\n", sizeof(dinParameterType->Name));
	// printf("[C] sizeof dinParameterType->ValueType = %ld\n", sizeof(dinParameterType->ValueType));
	// printf("[C] sizeof dinParameterType->boolValue = %ld\n", sizeof(dinParameterType->boolValue));
	// printf("[C] sizeof dinParameterType->byteValue = %ld\n", sizeof(dinParameterType->byteValue));
	// printf("[C] sizeof dinParameterType->shortValue = %ld\n", sizeof(dinParameterType->shortValue));
	// printf("[C] sizeof dinParameterType->intValue = %ld\n", sizeof(dinParameterType->intValue));
	// printf("[C] sizeof dinParameterType->physicalValue = %ld\n", sizeof(dinParameterType->physicalValue));
	// printf("[C] sizeof dinParameterType->stringValue = %ld\n", sizeof(dinParameterType->stringValue));

	// printf("\n");
	// printf("[C] offsetof(dinParameterType, Name) = %ld\n", offsetof(struct dinParameterType, Name));
	// printf("[C] offsetof(dinParameterType, ValueType) = %ld\n", offsetof(struct dinParameterType, ValueType));
	// printf("[C] offsetof(dinParameterType, boolValue) = %ld\n", offsetof(struct dinParameterType, boolValue));
	// printf("[C] offsetof(dinParameterType, shortValue) = %ld\n", offsetof(struct dinParameterType, shortValue));
	// printf("[C] offsetof(dinParameterType, intValue) = %ld\n", offsetof(struct dinParameterType, intValue));
	// printf("[C] offsetof(dinParameterType, physicalValue) = %ld\n", offsetof(struct dinParameterType, physicalValue));
	// printf("[C] offsetof(dinParameterType, stringValue) = %ld\n", offsetof(struct dinParameterType, stringValue));
	// printf("\n");


	// printf("[C] dinParameterType->Name.characters = %ls\n", dinParameterType->Name.characters);
	// printf("[C] dinParameterType->Name.charactersLen = %d\n", dinParameterType->Name.charactersLen);
	// printf("[C] dinParameterType->ValueType = %d\n", dinParameterType->ValueType);
	// printf("[C] dinParameterType->boolValue = %d\n", dinParameterType->boolValue);
	// printf("[C] dinParameterType->boolValue_isUsed = %d\n", dinParameterType->boolValue_isUsed);
	// printf("[C] dinParameterType->byteValue = %d\n", dinParameterType->byteValue);
	// printf("[C] dinParameterType->byteValue_isUsed = %d\n", dinParameterType->byteValue_isUsed);
	// printf("[C] dinParameterType->shortValue = %d\n", dinParameterType->shortValue);
	// printf("[C] dinParameterType->shortValue_isUsed = %d\n", dinParameterType->shortValue_isUsed);
	// printf("[C] dinParameterType->intValue = %d\n", dinParameterType->intValue);
	// printf("[C] dinParameterType->intValue_isUsed = %d\n", dinParameterType->intValue_isUsed);
	// printf("[C] dinParameterType->physicalValue.Multiplier = %d\n", dinParameterType->physicalValue.Multiplier);
	// printf("[C] dinParameterType->physicalValue.Unit = %d\n", dinParameterType->physicalValue.Unit);
	// printf("[C] dinParameterType->physicalValue.Unit_isUsed = %d\n", dinParameterType->physicalValue.Unit_isUsed);
	// printf("[C] dinParameterType->physicalValue.Value = %d\n", dinParameterType->physicalValue.Value);
	// printf("[C] dinParameterType->stringValue.characters = %ls\n", dinParameterType->stringValue.characters);
	// printf("[C] dinParameterType->stringValue.characters = %d\n", dinParameterType->stringValue.charactersLen);
	// validated


	dinParameterType->boolValue_isUsed = 0u;
	dinParameterType->byteValue_isUsed = 0u;
	dinParameterType->shortValue_isUsed = 0u;
	dinParameterType->intValue_isUsed = 0u;
	dinParameterType->physicalValue_isUsed = 0u;
	dinParameterType->stringValue_isUsed = 0u;
}

void init_dinChargingStatusReqType(struct dinChargingStatusReqType* dinChargingStatusReqType) {
	// validated
	(void)dinChargingStatusReqType; /* avoid unused warning */
}

void init_dinSignatureMethodType(struct dinSignatureMethodType* dinSignatureMethodType) {
	// printf("[C] sizeof dinSignatureMethodType = %ld\n", sizeof(struct dinSignatureMethodType));
	// validated
	dinSignatureMethodType->HMACOutputLength_isUsed = 0u;
	dinSignatureMethodType->ANY_isUsed = 0u;
}

void init_dinCertificateInstallationReqType(struct dinCertificateInstallationReqType* dinCertificateInstallationReqType) {
	// printf("[C] sizeof dinCertificateInstallationReqType = %ld\n", sizeof(struct dinCertificateInstallationReqType));
	// validated
	dinCertificateInstallationReqType->Id_isUsed = 0u;
}

void init_dinSalesTariffEntryType(struct dinSalesTariffEntryType* dinSalesTariffEntryType) {
	// printf("[C] sizeof dinSalesTariffEntryType = %ld\n", sizeof(struct dinSalesTariffEntryType));
	// printf("[C] dinSalesTariffEntryType->ConsumptionCost.array[0].Cost.array[1].amount = %d\n", dinSalesTariffEntryType->ConsumptionCost.array[0].Cost.array[1].amount);
	// validated
	dinSalesTariffEntryType->TimeInterval_isUsed = 0u;
	dinSalesTariffEntryType->RelativeTimeInterval_isUsed = 0u;
	dinSalesTariffEntryType->ConsumptionCost.arrayLen = 0u;
}

void init_dinServiceDiscoveryResType(struct dinServiceDiscoveryResType* dinServiceDiscoveryResType) {
	// printf("[C] sizeof dinServiceDiscoveryResType = %ld\n", sizeof(struct dinServiceDiscoveryResType));
	// validated
	dinServiceDiscoveryResType->ServiceList_isUsed = 0u;
}

void init_dinParameterSetType(struct dinParameterSetType* dinParameterSetType) {
	// printf("[C] sizeof dinParameterSetType = %ld\n", sizeof(struct dinParameterSetType));
	// printf("[C] sizeof dinParameterSetType->ParameterSetID = %ld\n", sizeof(dinParameterSetType->ParameterSetID));
	// printf("[C] sizeof dinParameterSetType->Parameter = %ld\n", sizeof(dinParameterSetType->Parameter));
	// printf("[C] sizeof dinParameterSetType->Parameter.array = %ld\n", sizeof(dinParameterSetType->Parameter.array));
	// printf("[C] sizeof dinParameterSetType->Parameter.arrayLen = %ld\n", sizeof(dinParameterSetType->Parameter.arrayLen));
	// printf("\n");
	// printf("[C] offset dinParameterSetType->Parameter.array = %ld\n", offsetof(struct dinParameterSetType, Parameter.array));
	// printf("[C] offset dinParameterSetType->Parameter.arrayLen = %ld\n", offsetof(struct dinParameterSetType, Parameter.arrayLen));
	// printf("[C] offset dinParameterSetType->ParameterSetID = %ld\n", offsetof(struct dinParameterSetType, ParameterSetID));
	

	// // Traverse array 
	// int i = 0;
	// for(; i < dinParameterSetType->Parameter.arrayLen; i++){
	// 	printf("[C] Parameter #%d\n", i+1);

	// 	printf("[C]\tName.characters = %ls\n", dinParameterSetType->Parameter.array[i].Name.characters);
	// 	printf("[C]\tName.charactersLen = %d\n", dinParameterSetType->Parameter.array[i].Name.charactersLen);
	// 	printf("[C]\tValueType = %d\n", dinParameterSetType->Parameter.array[i].ValueType);
	// 	printf("[C]\tboolValue = %d\n", dinParameterSetType->Parameter.array[i].boolValue);
	// 	printf("[C]\tboolValue_isUsed = %d\n", dinParameterSetType->Parameter.array[i].boolValue_isUsed);
	// 	printf("[C]\tbyteValue = %d\n", dinParameterSetType->Parameter.array[i].byteValue);
	// 	printf("[C]\tbyteValue_isUsed = %d\n", dinParameterSetType->Parameter.array[i].byteValue_isUsed);
	// 	printf("[C]\tshortValue = %d\n", dinParameterSetType->Parameter.array[i].shortValue);
	// 	printf("[C]\tshortValue_isUsed = %d\n", dinParameterSetType->Parameter.array[i].shortValue_isUsed);
	// 	printf("[C]\tintValue = %d\n", dinParameterSetType->Parameter.array[i].intValue);
	// 	printf("[C]\tintValue_isUsed = %d\n", dinParameterSetType->Parameter.array[i].intValue_isUsed);
	// }
	// validated
	dinParameterSetType->Parameter.arrayLen = 0u;
}

void init_dinCurrentDemandReqType(struct dinCurrentDemandReqType* dinCurrentDemandReqType) {
	// printf("Hello world");
	// printf("[C] sizeof dinCurrentDemandReqType = %ld\n", sizeof(struct dinCurrentDemandReqType));
	// validated
	dinCurrentDemandReqType->EVMaximumVoltageLimit_isUsed = 0u;
	dinCurrentDemandReqType->EVMaximumCurrentLimit_isUsed = 0u;
	dinCurrentDemandReqType->EVMaximumPowerLimit_isUsed = 0u;
	dinCurrentDemandReqType->BulkChargingComplete_isUsed = 0u;
	dinCurrentDemandReqType->RemainingTimeToFullSoC_isUsed = 0u;
	dinCurrentDemandReqType->RemainingTimeToBulkSoC_isUsed = 0u;
}

void init_dinPreChargeReqType(struct dinPreChargeReqType* dinPreChargeReqType) {
	// printf("[C] sizeof dinPreChargeReqType = %ld\n", sizeof(struct dinPreChargeReqType));
	// validated
	(void)dinPreChargeReqType; /* avoid unused warning */
}

void init_dinSignatureType(struct dinSignatureType* dinSignatureType) {
	// printf("[C] sizeof dinSignatureType = %ld\n", sizeof(struct dinSignatureType));
	// printf("[C] object id = %ls\n", dinSignatureType->Object.array[0].Id.characters);
	// validated
	dinSignatureType->Id_isUsed = 0u;
	dinSignatureType->KeyInfo_isUsed = 0u;
	dinSignatureType->Object.arrayLen = 0u;
}

void init_dinReferenceType(struct dinReferenceType* dinReferenceType) {
	// printf("%ls\n", dinReferenceType->DigestMethod.Algorithm.characters);
	// validated
	dinReferenceType->Id_isUsed = 0u;
	dinReferenceType->URI_isUsed = 0u;
	dinReferenceType->Type_isUsed = 0u;
	dinReferenceType->Transforms_isUsed = 0u;
}

void init_dinProfileEntryType(struct dinProfileEntryType* dinProfileEntryType) {
	// printf("[C] sizeof dinProfileEntryType = %ld\n", sizeof(struct dinProfileEntryType));
	// printf("[C] entry max power = %d\n", dinProfileEntryType->ChargingProfileEntryMaxPower);
	// validated
	(void)dinProfileEntryType; /* avoid unused warning */
}

void init_dinAnonType_V2G_Message(struct dinAnonType_V2G_Message* dinAnonType_V2G_Message) {
	printf("[C] sizeof dinAnonType_V2G_Message = %ld\n", sizeof(struct dinAnonType_V2G_Message));
	int i = 0;
	for(; i < dinAnonType_V2G_Message->Body.SessionSetupReq.EVCCID.bytesLen; i++){
		printf("%x ", dinAnonType_V2G_Message->Body.SessionSetupReq.EVCCID.bytes[i]);
	}
	printf("\n");
	(void)dinAnonType_V2G_Message; /* avoid unused warning */
}

void init_dinChargeParameterDiscoveryReqType(struct dinChargeParameterDiscoveryReqType* dinChargeParameterDiscoveryReqType) {
	// printf("[C] sizeof dinChargeParameterDiscoveryReqType = %ld\n", sizeof(struct dinChargeParameterDiscoveryReqType));
	// printf("[C] BulkSoC = %d\n", dinChargeParameterDiscoveryReqType->DC_EVChargeParameter.BulkSOC);
	// validated
	dinChargeParameterDiscoveryReqType->EVChargeParameter_isUsed = 0u;
	dinChargeParameterDiscoveryReqType->AC_EVChargeParameter_isUsed = 0u;
	dinChargeParameterDiscoveryReqType->DC_EVChargeParameter_isUsed = 0u;
}

void init_dinConsumptionCostType(struct dinConsumptionCostType* dinConsumptionCostType) {
	// printf("[C] dinConsumptionCostType->Cost.array[1].amount = %d\n", dinConsumptionCostType->Cost.array[1].amount);
	// validated
	dinConsumptionCostType->Cost.arrayLen = 0u;
}

void init_dinRSAKeyValueType(struct dinRSAKeyValueType* dinRSAKeyValueType) {
	// printf("[C] sizeof dinRSAKeyValueType = %ld\n", sizeof(struct dinRSAKeyValueType));
	// validated
	(void)dinRSAKeyValueType; /* avoid unused warning */
}

void init_dinServiceType(struct dinServiceType* dinServiceType) {
	// printf("[C] sizeof dinServiceType = %ld\n", sizeof(struct dinServiceType));
	// printf("[C] service scope = %ls\n", dinServiceType->ServiceTag.ServiceScope.characters);
	// validated

	(void)dinServiceType; /* avoid unused warning */
}

void init_dinServiceTagListType(struct dinServiceTagListType* dinServiceTagListType) {
	// printf("[C] sizeof dinServiceTagListType = %ld\n", sizeof(struct dinServiceTagListType));
	// printf("[C] scope of 2 = %ls\n", dinServiceTagListType->Service.array[1].ServiceTag.ServiceScope.characters);
	// validated
	dinServiceTagListType->Service.arrayLen = 0u;
}

void init_dinEVSEStatusType(struct dinEVSEStatusType* dinEVSEStatusType) {
	(void)dinEVSEStatusType; /* avoid unused warning */
}

void init_dinSessionSetupResType(struct dinSessionSetupResType* dinSessionSetupResType) {
	// printf("[C] sizeof dinSessionSetupResType = %ld\n", sizeof(struct dinSessionSetupResType));
	// printf("[C] datetime now: %ld\n", dinSessionSetupResType->DateTimeNow);
	// validated
	dinSessionSetupResType->DateTimeNow_isUsed = 0u;
}

void init_dinEVPowerDeliveryParameterType(struct dinEVPowerDeliveryParameterType* dinEVPowerDeliveryParameterType) {
	// validated
	(void)dinEVPowerDeliveryParameterType; /* avoid unused warning */
}

void init_dinX509IssuerSerialType(struct dinX509IssuerSerialType* dinX509IssuerSerialType) {
	// printf("[C] sizeof dinX509IssuerSerialType = %ld\n", sizeof(struct dinX509IssuerSerialType));
	// printf("[C] dinX509IssuerSerialType->X509IssuerName.characters = %ls\n", dinX509IssuerSerialType->X509IssuerName.characters);
	// printf("[C] dinX509IssuerSerialType->X509IssuerName.charactersLen = %d\n", dinX509IssuerSerialType->X509IssuerName.charactersLen);
	// printf("[C] dinX509IssuerSerialType->X509SerialNumber = %ld\n", dinX509IssuerSerialType->X509SerialNumber);
	// validated

	(void)dinX509IssuerSerialType; /* avoid unused warning */
}

void init_dinSelectedServiceType(struct dinSelectedServiceType* dinSelectedServiceType) {
	dinSelectedServiceType->ParameterSetID_isUsed = 0u;
}

void init_dinMeteringReceiptResType(struct dinMeteringReceiptResType* dinMeteringReceiptResType) {
	// printf("[C] sizeof dinMeteringReceiptResType = %ld\n", sizeof(struct dinMeteringReceiptResType));
	// printf("[C] EVSE Notification = %d\n", dinMeteringReceiptResType->AC_EVSEStatus.EVSENotification);
	// validated
	(void)dinMeteringReceiptResType; /* avoid unused warning */
}

void init_dinDC_EVStatusType(struct dinDC_EVStatusType* dinDC_EVStatusType) {
	// printf("[C] sizeof dinDC_EVStatusType = %ld\n", sizeof(struct dinDC_EVStatusType));
	// printf("[C] dinDC_EVStatusType->EVCabinConditioning = %d\n", dinDC_EVStatusType->EVCabinConditioning);
	// printf("[C] dinDC_EVStatusType->EVCabinConditioning_isUsed = %d\n", dinDC_EVStatusType->EVCabinConditioning_isUsed);
	// printf("[C] dinDC_EVStatusType->EVErrorCode = %d\n", dinDC_EVStatusType->EVErrorCode);
	// printf("[C] dinDC_EVStatusType->EVReady = %d\n", dinDC_EVStatusType->EVReady);
	// printf("[C] dinDC_EVStatusType->EVRESSConditioning = %d\n", dinDC_EVStatusType->EVRESSConditioning);
	// printf("[C] dinDC_EVStatusType->EVRESSConditioning_isUsed = %d\n", dinDC_EVStatusType->EVRESSConditioning_isUsed);
	// printf("[C] dinDC_EVStatusType->EVErrorCode = %d\n", dinDC_EVStatusType->EVErrorCode);
	// printf("[C] dinDC_EVStatusType->EVRESSSOC = %d\n", dinDC_EVStatusType->EVRESSSOC);
	// validated

	dinDC_EVStatusType->EVCabinConditioning_isUsed = 0u;
	dinDC_EVStatusType->EVRESSConditioning_isUsed = 0u;
}

void init_dinPhysicalValueType(struct dinPhysicalValueType* dinPhysicalValueType) {

	// printf("[C] sizeof dinPhysicalValueType = %ld\n", sizeof(struct dinPhysicalValueType));
	// printf("[C] sizeof dinPhysicalValueType->Multiplier = %ld\n", sizeof(dinPhysicalValueType->Multiplier));
	// printf("[C] sizeof dinPhysicalValueType->Unit = %ld\n", sizeof(dinPhysicalValueType->Unit));
	// printf("[C] sizeof dinPhysicalValueType->Value = %ld\n", sizeof(dinPhysicalValueType->Value));

	// printf("[C] offset dinPhysicalValueType->Multiplier = %ld\n", offsetof(struct dinPhysicalValueType, Multiplier));
	// printf("[C] offset dinPhysicalValueType->Unit = %ld\n", offsetof(struct dinPhysicalValueType, Unit));
	// printf("[C] offset dinPhysicalValueType->Value = %ld\n", offsetof(struct dinPhysicalValueType, Value));

	// printf("\n");
	// printf("[C] dinPhysicalValueType->Multiplier = %d\n", dinPhysicalValueType->Multiplier);
	// printf("[C] dinPhysicalValueType->Unit = %d\n", dinPhysicalValueType->Unit);
	// printf("[C] dinPhysicalValueType->Unit_isUsed = %d\n", dinPhysicalValueType->Unit_isUsed);
	// printf("[C] dinPhysicalValueType->Value = %d\n", dinPhysicalValueType->Value);
	// validated 

	dinPhysicalValueType->Unit_isUsed = 0u;
}

void init_dinManifestType(struct dinManifestType* dinManifestType) {
	// printf("[C] sizeof dinManifestType = %ld\n", sizeof(struct dinManifestType));
	// validated
	dinManifestType->Id_isUsed = 0u;
	dinManifestType->Reference.arrayLen = 0u;
}

void init_dinPMaxScheduleEntryType(struct dinPMaxScheduleEntryType* dinPMaxScheduleEntryType) {
	// printf("[C] sizeof dinPMaxScheduleEntryType = %ld\n", sizeof(struct dinPMaxScheduleEntryType));
	// printf("[C] pmax = %d\n", dinPMaxScheduleEntryType->PMax);
	// validated
	dinPMaxScheduleEntryType->TimeInterval_isUsed = 0u;
	dinPMaxScheduleEntryType->RelativeTimeInterval_isUsed = 0u;
}

void init_dinServiceParameterListType(struct dinServiceParameterListType* dinServiceParameterListType) {
	// printf("[C] sizeof dinServiceParameterListType = %ld\n", sizeof(struct dinServiceParameterListType));

	// printf("[C] dinServiceParameterListType->ParameterSet.arrayLen = %d\n", dinServiceParameterListType->ParameterSet.arrayLen);
	// validated
	dinServiceParameterListType->ParameterSet.arrayLen = 0u;
}

void init_dinSignatureValueType(struct dinSignatureValueType* dinSignatureValueType) {
	// printf("[C] sizeof dinSignatureValueType = %ld\n", sizeof(struct dinSignatureValueType));
	// printf("[C] dinSignatureValueType->Id = %ls\n", dinSignatureValueType->Id.characters);
	// validated
	dinSignatureValueType->Id_isUsed = 0u;
}

void init_dinPaymentOptionsType(struct dinPaymentOptionsType* dinPaymentOptionsType) {
	// validated
	dinPaymentOptionsType->PaymentOption.arrayLen = 0u;
}

void init_dinServiceTagType(struct dinServiceTagType* dinServiceTagType) {
	// printf("[C] sizeof dinServiceTagType = %ld\n", sizeof(struct dinServiceTagType));
	// printf("[C] scope = %ls\n", dinServiceTagType->ServiceScope.characters);
	// validated
	dinServiceTagType->ServiceName_isUsed = 0u;
	dinServiceTagType->ServiceScope_isUsed = 0u;
}

void init_dinAC_EVSEStatusType(struct dinAC_EVSEStatusType* dinAC_EVSEStatusType) {
	// printf("[C] sizeof dinAC_EVSEStatusType: %ld\n", sizeof(struct dinAC_EVSEStatusType));
	// printf("[C] pointer of dinAC_EVSEStatusType: %p\n",  dinAC_EVSEStatusType);

	// printf("[C] dinAC_EVSEStatusType->RCD = %d\n",  dinAC_EVSEStatusType->RCD);
	// printf("[C] dinAC_EVSEStatusType->EVSENotification = %d\n",  dinAC_EVSEStatusType->EVSENotification);
	// printf("[C] dinAC_EVSEStatusType->NotificationMaxDelay = %d\n",  dinAC_EVSEStatusType->NotificationMaxDelay);
	// printf("[C] dinAC_EVSEStatusType->PowerSwitchClosed = %d\n",  dinAC_EVSEStatusType->PowerSwitchClosed);

	// validated
	(void)dinAC_EVSEStatusType; /* avoid unused warning */
}

void init_dinCertificateUpdateReqType(struct dinCertificateUpdateReqType* dinCertificateUpdateReqType) {
	// printf("[C] sizeof dinCertificateUpdateReqType: %ld\n", sizeof(struct dinCertificateUpdateReqType));
	// printf("[C] ListOfRootCertificateIDs = %ls\n", dinCertificateUpdateReqType->ListOfRootCertificateIDs.RootCertificateID.array[2].characters);
	// validated
	dinCertificateUpdateReqType->Id_isUsed = 0u;
}

void init_dinServicePaymentSelectionResType(struct dinServicePaymentSelectionResType* dinServicePaymentSelectionResType) {
	// printf("[C] sizeof dinServicePaymentSelectionResType: %ld\n", sizeof(struct dinServicePaymentSelectionResType));
	// printf("[C] Response code: %d\n", dinServicePaymentSelectionResType->ResponseCode);
	// validated
	(void)dinServicePaymentSelectionResType; /* avoid unused warning */
}

void init_dinSAScheduleTupleType(struct dinSAScheduleTupleType* dinSAScheduleTupleType) {
	// printf("[C] amount = %d\n", dinSAScheduleTupleType->SalesTariff.SalesTariffEntry.array[0].ConsumptionCost.array[0].Cost.array[1].amount);
	// validated
	dinSAScheduleTupleType->SalesTariff_isUsed = 0u;
}

void init_dinChargingProfileType(struct dinChargingProfileType* dinChargingProfileType) {
	// printf("[C] sizeof dinChargingProfileType: %ld\n", sizeof(struct dinChargingProfileType));
	// printf("[C] maxpower = %d\n", dinChargingProfileType->ProfileEntry.array[1].ChargingProfileEntryMaxPower);
	// validated
	dinChargingProfileType->ProfileEntry.arrayLen = 0u;
}

void init_dinServiceDiscoveryReqType(struct dinServiceDiscoveryReqType* dinServiceDiscoveryReqType) {
	// printf("[C] sizeof dinServiceDiscoveryReqType: %ld\n", sizeof(struct dinServiceDiscoveryReqType));
	// validated
	dinServiceDiscoveryReqType->ServiceScope_isUsed = 0u;
	dinServiceDiscoveryReqType->ServiceCategory_isUsed = 0u;
}

void init_dinAC_EVSEChargeParameterType(struct dinAC_EVSEChargeParameterType* dinAC_EVSEChargeParameterType) {
	// printf("[C] sizeof dinAC_EVSEChargeParameterType = %ld\n", sizeof(struct dinAC_EVSEChargeParameterType));
	// validated
	(void)dinAC_EVSEChargeParameterType; /* avoid unused warning */
}

void init_dinKeyInfoType(struct dinKeyInfoType* dinKeyInfoType) {
	// printf("[C] sizeof dinKeyInfoType = %ld\n", sizeof(struct dinKeyInfoType));
	// printf("[C] any = %ls\n", dinKeyInfoType->ANY.characters);
	// validated
	dinKeyInfoType->Id_isUsed = 0u;
	dinKeyInfoType->KeyName.arrayLen = 0u;
	dinKeyInfoType->KeyValue.arrayLen = 0u;
	dinKeyInfoType->RetrievalMethod.arrayLen = 0u;
	dinKeyInfoType->X509Data.arrayLen = 0u;
	dinKeyInfoType->PGPData.arrayLen = 0u;
	dinKeyInfoType->SPKIData.arrayLen = 0u;
	dinKeyInfoType->MgmtData.arrayLen = 0u;
	dinKeyInfoType->ANY_isUsed = 0u;
}

void init_dinPaymentDetailsReqType(struct dinPaymentDetailsReqType* dinPaymentDetailsReqType) {
	// printf("[C] sizeof dinPaymentDetailsReqType = %ld\n", sizeof(struct dinPaymentDetailsReqType));
	// validated
	(void)dinPaymentDetailsReqType; /* avoid unused warning */
}

void init_dinCableCheckResType(struct dinCableCheckResType* dinCableCheckResType) {
	// printf("[C] sizeof dinCableCheckResType = %ld\n", sizeof(struct dinCableCheckResType));
	// validated
	(void)dinCableCheckResType; /* avoid unused warning */
}

void init_dinObjectType(struct dinObjectType* dinObjectType) {
	// printf("[C] sizeof dinObjectType = %ld\n", sizeof(struct dinObjectType));
	// validated
	dinObjectType->Id_isUsed = 0u;
	dinObjectType->MimeType_isUsed = 0u;
	dinObjectType->Encoding_isUsed = 0u;
	dinObjectType->ANY_isUsed = 0u;
}

void init_dinSessionStopResType(struct dinSessionStopResType* dinSessionStopResType) {
	// validated
	(void)dinSessionStopResType; /* avoid unused warning */
}

void init_dinSignedInfoType(struct dinSignedInfoType* dinSignedInfoType) {
	// printf("[C] sizeof dinSignedInfoType = %ld\n", sizeof(struct dinSignedInfoType));
	// printf("[C] %ls\n", dinSignedInfoType->Reference.array[0].Transforms.Transform.array[0].XPath.array[0].characters);
	// printf("[C] CanonicalizationMethod.ANY = %ls\n", dinSignedInfoType->CanonicalizationMethod.ANY.characters);
	// validated
	dinSignedInfoType->Id_isUsed = 0u;
	dinSignedInfoType->Reference.arrayLen = 0u;
}

void init_dinSalesTariffType(struct dinSalesTariffType* dinSalesTariffType) {
	// printf("[C] dinSalesTariffType->SalesTariffEntry.array[0].ConsumptionCost.array[0].Cost.array[1].amount = %d\n", dinSalesTariffType->SalesTariffEntry.array[0].ConsumptionCost.array[0].Cost.array[1].amount);
	// validated
	dinSalesTariffType->SalesTariffDescription_isUsed = 0u;
	dinSalesTariffType->SalesTariffEntry.arrayLen = 0u;
}

void init_dinCostType(struct dinCostType* dinCostType) {
	// printf("[C] sizeof dinCostType = %ld\n", sizeof(struct dinCostType));
	// printf("[C] costKind = %d\n", dinCostType->costKind);
	// printf("[C] amount = %d\n", dinCostType->amount);
	// printf("[C] amountMultiplier = %d\n", dinCostType->amountMultiplier);
	// printf("[C] amountMultiplier_isUsed = %d\n", dinCostType->amountMultiplier_isUsed);
	// validated
	dinCostType->amountMultiplier_isUsed = 0u;
}

void init_dinServiceChargeType(struct dinServiceChargeType* dinServiceChargeType) {
	// printf("[C] sizeof dinServiceChargeType = %ld\n", sizeof(struct dinServiceChargeType));
	// validated
	(void)dinServiceChargeType; /* avoid unused warning */
}

void init_dinDC_EVSEStatusType(struct dinDC_EVSEStatusType* dinDC_EVSEStatusType) {
	// printf("[C] sizeof dinDC_EVSEStatusType = %ld\n", sizeof(struct dinDC_EVSEStatusType));
	// printf("[C] pointer of dinDC_EVSEStatusType = %p\n", dinDC_EVSEStatusType);

	// printf("[C] dinDC_EVSEStatusType->EVSEIsolationStatus = %d\n", dinDC_EVSEStatusType->EVSEIsolationStatus);
	// printf("[C] dinDC_EVSEStatusType->EVSEIsolationStatus_isUsed = %d\n", dinDC_EVSEStatusType->EVSEIsolationStatus_isUsed);
	// printf("[C] dinDC_EVSEStatusType->EVSENotification = %d\n", dinDC_EVSEStatusType->EVSENotification);
	// printf("[C] dinDC_EVSEStatusType->EVSEStatusCode = %d\n", dinDC_EVSEStatusType->EVSEStatusCode);
	// printf("[C] dinDC_EVSEStatusType->NotificationMaxDelay = %d\n", dinDC_EVSEStatusType->NotificationMaxDelay);
	// validated
	dinDC_EVSEStatusType->EVSEIsolationStatus_isUsed = 0u;
}

void init_dinRetrievalMethodType(struct dinRetrievalMethodType* dinRetrievalMethodType) {
	// printf("[C] sizeof dinRetrievalMethodType = %ld\n", sizeof(struct dinRetrievalMethodType));
	// printf("[C] XPath = %ls\n", dinRetrievalMethodType->Transforms.Transform.array[0].XPath.array[0].characters);
	// validated
	dinRetrievalMethodType->URI_isUsed = 0u;
	dinRetrievalMethodType->Type_isUsed = 0u;
	dinRetrievalMethodType->Transforms_isUsed = 0u;
}

void init_dinNotificationType(struct dinNotificationType* dinNotificationType) {
	// printf("[C] sizeof dinNotificationType = %ld\n", sizeof(struct dinNotificationType));
	// validated
	dinNotificationType->FaultMsg_isUsed = 0u;
}

void init_dinPGPDataType(struct dinPGPDataType* dinPGPDataType) {
	// printf("[C] sizeof dinPGPDataType = %ld\n", sizeof(struct dinPGPDataType));
	// printf("[C] ANY = %ls\n", dinPGPDataType->ANY.characters);
	// validated
	dinPGPDataType->PGPKeyID_isUsed = 0u;
	dinPGPDataType->PGPKeyPacket_isUsed = 0u;
	dinPGPDataType->ANY_isUsed = 0u;
}

void init_dinCertificateInstallationResType(struct dinCertificateInstallationResType* dinCertificateInstallationResType) {
	// printf("[C] sizeof dinCertificateInstallationResType = %ld\n", sizeof(struct dinCertificateInstallationResType));
	// printf("[C] dinCertificateInstallationResType->ContractID.characters = %ls\n", dinCertificateInstallationResType->ContractID.characters);
	// validated
	(void)dinCertificateInstallationResType; /* avoid unused warning */
}

void init_dinSignaturePropertyType(struct dinSignaturePropertyType* dinSignaturePropertyType) {
	// printf("[C] dinSignaturePropertyType->ANY = %ls\n", dinSignaturePropertyType->ANY.characters);
	// printf("[C] dinSignaturePropertyType->ANY_isUsed = %d\n", dinSignaturePropertyType->ANY_isUsed);
	// printf("[C] dinSignaturePropertyType->Id = %ls\n", dinSignaturePropertyType->Id.characters);
	// printf("[C] dinSignaturePropertyType->Id_isUsed = %d\n", dinSignaturePropertyType->Id_isUsed);
	// printf("[C] dinSignaturePropertyType->Target = %ls\n", dinSignaturePropertyType->Target.characters);
	// validated

	dinSignaturePropertyType->Id_isUsed = 0u;
	dinSignaturePropertyType->ANY_isUsed = 0u;
}

void init_dinMeterInfoType(struct dinMeterInfoType* dinMeterInfoType) {
	// printf("[C] sizeof dinMeterInfoType = %ld\n", sizeof(struct dinMeterInfoType));
	// printf("[C] sizeof dinMeterInfoType->MeterID = %ld\n", sizeof(dinMeterInfoType->MeterID));
	// printf("[C] sizeof dinMeterInfoType->MeterReading = %ld\n", sizeof(dinMeterInfoType->MeterReading));
	// printf("[C] sizeof dinMeterInfoType->SigMeterReading = %ld\n", sizeof(dinMeterInfoType->SigMeterReading));
	// printf("[C] sizeof dinMeterInfoType->MeterStatus = %ld\n", sizeof(dinMeterInfoType->MeterStatus));
	// printf("[C] sizeof dinMeterInfoType->TMeter = %ld\n", sizeof(dinMeterInfoType->TMeter));
	// printf("[C] offset dinMeterInfoType->MeterID = %ld\n", offsetof(struct dinMeterInfoType, MeterID));
	// printf("[C] offset dinMeterInfoType->MeterReading = %ld\n", offsetof(struct dinMeterInfoType, MeterReading));
	// printf("[C] offset dinMeterInfoType->SigMeterReading = %ld\n", offsetof(struct dinMeterInfoType, SigMeterReading));
	// printf("[C] offset dinMeterInfoType->MeterStatus = %ld\n", offsetof(struct dinMeterInfoType, MeterStatus));
	// printf("[C] offset dinMeterInfoType->TMeter = %ld\n", offsetof(struct dinMeterInfoType, TMeter));
	// printf("\n");
	// printf("[C] dinMeterInfoType->MeterID.characters = %ls\n", dinMeterInfoType->MeterID.characters);
	// printf("[C] dinMeterInfoType->MeterID.charactersLen = %d\n", dinMeterInfoType->MeterID.charactersLen);
	// printf("[C] dinMeterInfoType->MeterReading.Multiplier = %d\n", dinMeterInfoType->MeterReading.Multiplier);
	// printf("[C] dinMeterInfoType->MeterReading.Unit = %d\n", dinMeterInfoType->MeterReading.Unit);
	// printf("[C] dinMeterInfoType->MeterReading.Unit_isUsed = %d\n", dinMeterInfoType->MeterReading.Unit_isUsed);
	// printf("[C] dinMeterInfoType->MeterReading.Value = %d\n", dinMeterInfoType->MeterReading.Value);
	// printf("[C] dinMeterInfoType->MeterReading_isUsed = %d\n", dinMeterInfoType->MeterReading_isUsed);
	// printf("[C] dinMeterInfoType->SigMeterReading_isUsed = %d\n", dinMeterInfoType->SigMeterReading_isUsed);
	// printf("[C] dinMeterInfoType->MeterID.charactersLen = %d\n", dinMeterInfoType->MeterID.charactersLen);
	// printf("[C] dinMeterInfoType->MeterStatus = %d\n", dinMeterInfoType->MeterStatus);
	// printf("[C] dinMeterInfoType->MeterStatus_isUsed = %d\n", dinMeterInfoType->MeterStatus_isUsed);
	// printf("[C] dinMeterInfoType->TMeter = %d\n", dinMeterInfoType->TMeter);
	// printf("[C] dinMeterInfoType->TMeter_isUsed = %d\n", dinMeterInfoType->TMeter_isUsed);
	// validated

	dinMeterInfoType->MeterReading_isUsed = 0u;
	dinMeterInfoType->SigMeterReading_isUsed = 0u;
	dinMeterInfoType->MeterStatus_isUsed = 0u;
	dinMeterInfoType->TMeter_isUsed = 0u;
}

void init_dinSubCertificatesType(struct dinSubCertificatesType* dinSubCertificatesType) {
	// printf("[C] dinSubCertificatesType->Certificate.arrayLen = %d\n", dinSubCertificatesType->Certificate.arrayLen);
	// validated
	dinSubCertificatesType->Certificate.arrayLen = 0u;
}



#endif /* DEPLOY_DIN_CODEC */

#endif

