/*
 * Copyright (C) 2007-2018 Siemens AG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 0.9.4
 * @contact Richard.Kuntschke@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: V2G_CI_AppProtocol.xsd</p>
 *
 *
 ********************************************************************/



#include <stdint.h>

#include "appHandEXIDatatypes.h"
#include "../codec/EXITypes.h"


#ifndef EXI_appHand_DATATYPES_C
#define EXI_appHand_DATATYPES_C



void init_appHandEXIDocument(struct appHandEXIDocument* exiDoc) {
	// printf("[C] struct pointer: %p\n", exiDoc);
	// printf("[C] sizeof appHandAppProtocolType: %ld\n", sizeof(struct appHandEXIDocument));
	// printf("[C] supportedAppProtocolReq_isUsed = : %d\n", exiDoc->supportedAppProtocolReq_isUsed);
	// printf("[C] supportedAppProtocolRes_isUsed = : %d\n", exiDoc->supportedAppProtocolRes_isUsed);
	
	exiDoc->supportedAppProtocolReq_isUsed = 0u;
	exiDoc->supportedAppProtocolRes_isUsed = 0u;

	// printf("[C] supportedAppProtocolReq_isUsed = : %d\n", exiDoc->supportedAppProtocolReq_isUsed);
	// printf("[C] supportedAppProtocolRes_isUsed = : %d\n", exiDoc->supportedAppProtocolRes_isUsed);

}

void init_appHandAppProtocolType(struct appHandAppProtocolType* appHandAppProtocolType) {
	// printf("[C] struct pointer: %p\n", appHandAppProtocolType);
	// printf("[C] sizeof appHandAppProtocolType: %ld\n", sizeof(struct appHandAppProtocolType));
	// printf("[C] ProtocolNamespace.characters=%ls\n", appHandAppProtocolType->ProtocolNamespace.characters);
	// printf("[C] VersionNumberMajor=%d\n", appHandAppProtocolType->VersionNumberMajor);
	// printf("[C] VersionNumberMinor=%d\n", appHandAppProtocolType->VersionNumberMinor);
	// printf("[C] SchemaID=%d\n", appHandAppProtocolType->SchemaID);
	// printf("[C] Priority=%d\n", appHandAppProtocolType->Priority);
}

void init_appHandAnonType_supportedAppProtocolReq(struct appHandAnonType_supportedAppProtocolReq* appHandAnonType_supportedAppProtocolReq) {
	// printf("[C] struct pointer: %p\n", appHandAnonType_supportedAppProtocolReq);
	// printf("[C] sizeof appHandAnonType_supportedAppProtocolReq: %ld\n", sizeof(struct appHandAnonType_supportedAppProtocolReq));
	// printf("[C] appHandAnonType_supportedAppProtocolReq->AppProtocol.arrayLen = %d\n", appHandAnonType_supportedAppProtocolReq->AppProtocol.arrayLen);

	appHandAnonType_supportedAppProtocolReq->AppProtocol.arrayLen = 0u;
}

void init_appHandAnonType_supportedAppProtocolRes(struct appHandAnonType_supportedAppProtocolRes* appHandAnonType_supportedAppProtocolRes) {
	// printf("[C] sizeof(appHandAnonType_supportedAppProtocolRes) = %ld\n", sizeof(appHandAnonType_supportedAppProtocolRes));
	// printf("[C] sizeof(appHandAnonType_supportedAppProtocolRes->ResponseCode) = %ld\n", sizeof(appHandAnonType_supportedAppProtocolRes->ResponseCode));
	// printf("[C] sizeof(appHandAnonType_supportedAppProtocolRes->SchemaID) = %ld\n", sizeof(appHandAnonType_supportedAppProtocolRes->SchemaID));


	// printf("[C] appHandAnonType_supportedAppProtocolRes->ResponseCode = %d\n", appHandAnonType_supportedAppProtocolRes->ResponseCode);
	// printf("[C] appHandAnonType_supportedAppProtocolRes->SchemaID = %d\n", appHandAnonType_supportedAppProtocolRes->SchemaID);
	// printf("[C] appHandAnonType_supportedAppProtocolRes->SchemaID_isUsed = %d\n", appHandAnonType_supportedAppProtocolRes->SchemaID_isUsed);
	

	appHandAnonType_supportedAppProtocolRes->SchemaID_isUsed = 0u;
}





#endif

